/* ELECTRONBENCH v1.3.1-rc.1 — GPL-3.0-only */
'use strict';
(()=>{
const E=window.EB,$=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='electronbench-project-v1',BACKUP=KEY+'-previous',PREF='electronbench-preferences';
let project=E.sample(),selected=null,selectedEdge=null,pending=null,history=[],future=[],tool='select',tab='preview',sim=null,running=false,simTime=0,simInputs={},watch='',samples=[],lastFrame=0,accumulator=0,lastPaint=0,saveTimer,drag=null,dirty=false,recoveryRaw=null,restoredView=false;
let prefs={theme:'dark',library:innerWidth>900,inspector:innerWidth>1100,dock:true,mode:'easy',dockHeight:253};
let selection=new Set();
try{const p=JSON.parse(localStorage.getItem(PREF));if(p)prefs={...prefs,...p};}catch{}
try{const raw=localStorage.getItem(KEY);if(raw){project=E.importProject(JSON.parse(raw));restoredView=true;}}catch{try{recoveryRaw=localStorage.getItem(KEY);}catch{}recoveryRaw=recoveryRaw||'Storage is unavailable';project=E.blank();}
const uid=prefix=>prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const node=id=>project.nodes.find(n=>n.id===id),say=message=>{$('status').textContent=message;$('status').title=message;};
const fmt=v=>typeof v==='boolean'?(v?'HIGH':'LOW'):Number.isFinite(v)?Number(v.toFixed(2)).toString():'—';
function prefSave(){try{localStorage.setItem(PREF,JSON.stringify(prefs));}catch{}}
function mark(){dirty=true;$('saveState').textContent='● Unsaved';$('saveState').classList.remove('error');clearTimeout(saveTimer);saveTimer=setTimeout(save,250);}
function save(){
 if(recoveryRaw)return;
 $('saveState').textContent='● Saving…';
 try{const json=JSON.stringify(project),old=localStorage.getItem(KEY);if(old&&old!==json){try{localStorage.setItem(BACKUP,old);}catch{}}localStorage.setItem(KEY,json);dirty=false;$('saveState').textContent='● Saved locally';$('saveState').classList.remove('error');}
 catch{$('saveState').textContent='● Save failed — export JSON';$('saveState').classList.add('error');say('Local storage is full or blocked. Save JSON to preserve this project.');}
}
function checkpoint(){history.push(E.clone(project));if(history.length>60)history.shift();future=[];}
function edit(fn){const focus=document.activeElement;const prop=focus?.dataset?.prop;const before=E.clone(project),oldHistory=[...history],oldFuture=[...future];checkpoint();stopPreview(true);try{fn();}catch(error){project=before;history=oldHistory;future=oldFuture;render();throw error;}pending=null;render();mark();if(prop)$('inspectorBody').querySelector('[data-prop="'+prop+'"]')?.focus();window.dispatchEvent(new CustomEvent('eb:change'));}
function stopPreview(reset=false){running=false;$('run').textContent='▶ Run preview';$('modeBadge').textContent='EDIT';$('modeBadge').classList.remove('running');lastFrame=0;accumulator=0;if(reset){sim=null;simTime=0;samples=[];updateLive();}}
function replaceProject(next){pending=null;selection.clear();checkpoint();stopPreview(true);project=next;selected=null;selectedEdge=null;simInputs={};watch='';render();fit();mark();}
let modalOpener=null;
function modal(title,html){if(!$('modal').open)modalOpener=document.activeElement.closest('#projectMenu')?$('projectMenu').querySelector('summary'):document.activeElement;$('modalTitle').textContent=title;$('modalBody').innerHTML=html;if(!$('modal').open)$('modal').showModal();$('modalTitle').focus();}
function closeModal(){$('modal').close();if(modalOpener?.isConnected)modalOpener.focus();}
$('modal').addEventListener('close',()=>{if(modalOpener?.isConnected)modalOpener.focus();});
function confirmReplace(title,action){if(!project.nodes.length){action();return;}modal(title,'<p>The current project can be recovered with Undo. Save JSON first if you want a separate copy.</p><div class="modal-actions"><button id="confirmChange" class="primary">Continue</button><button id="cancelChange">Cancel</button></div>');$('confirmChange').onclick=()=>{closeModal();action();};$('cancelChange').onclick=closeModal;}
function showStarters(){modal('A small idea. A working program.',`<p>Start with a connected program for <strong>${esc(E.board(project).name)}</strong>. Network examples use an ESP32 target.</p><div id="starterGrid" class="starter-grid"><button class="starter" data-starter="blink"><span class="starter-icon">◷</span><span><strong>A little heartbeat</strong><small>Clock → built-in LED. Your first visual program.</small></span></button><button class="starter" data-starter="servo"><span class="starter-icon">◴</span><span><strong>Follow the dial</strong><small>Potentiometer → range mapping → servo position.</small></span></button><button class="starter" data-starter="button"><span class="starter-icon">↥</span><span><strong>One press, one pulse</strong><small>Button → debounce → timed pulse → LED.</small></span></button><button class="starter" data-starter="sensor"><span class="starter-icon">°C</span><span><strong>Temperature on the bench</strong><small>MCP9808 sensor → SSD1306 OLED, with telemetry.</small></span></button></div><p>Opening a starter replaces the canvas. Undo restores your previous project.</p>`);$('modalBody').querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>{replaceProject(window.EBPolish.starter(b.dataset.starter,project.board));closeModal();say('Starter opened. Run preview to explore its behavior.');});window.EBNetworkUI?.extendStarters();}
function showHelp(){modal('Welcome to the bench',`<div class="notice">Choose a board → connect behavior → preview → export firmware.</div><h3>Make your first connection</h3><p>Add components from the left. Click an output port, then a matching input. Round green ports carry Boolean signals; square amber ports carry numbers. You can also assign a connection in the inspector using a dropdown.</p><h3>Move around</h3><p>Drag a component by its heading. Use Pan to move the canvas, or hold Space while dragging empty space. Scroll to zoom; Fit shows the full program. Arrow keys move a focused component. Delete removes it. Ctrl/⌘ Z undoes edits.</p><h3>Try the program</h3><p>Run preview uses virtual inputs. A button can be latched pressed/released; an analog slider supplies a reading. Step advances 10 ms. Reset returns time and internal states to zero while keeping your input settings. Editing a component stops and resets the preview.</p><h3>Put it on a board</h3><p>Export Arduino downloads a sketch for the selected board. Open it in Arduino IDE, select the matching board and port, and upload. AVR servo projects require the Arduino Servo library. Project → Download project bundle includes exact library versions and an Arduino CLI build profile. Build / Upload uses the included local companion. Start it on the computer connected to the board, then open its pairing link.</p><h3>Go further</h3><p>Advanced mode exposes sensor, bus, state, and custom-code components. Project tools provides test scenarios, reusable modules, revisions, and separate evidence and assumptions registers. Live serial reads serial data through Web Serial where supported, or through the local companion. The companion uses pinned Arduino CLI build profiles; initial downloads need an internet connection.</p><h3>Keep your work</h3><p>Changes save in this browser. Save JSON makes a portable backup, including notes and the graph. Open JSON imports it. Different website addresses have separate local workspaces. New starts a genuinely empty project.</p><h3>Know the boundary</h3><p>Preview models program logic, not electrical behavior, real servo movement, or precise MCU timing. Pin map describes physical assignments; canvas connections describe signals. Feedback requires a Sample delay or Boolean delay component; these projects evaluate every 10 ms. Exported C++ does not round-trip back to a diagram.</p><p>ELECTRONBENCH v${E.VERSION} · GNU GPL v3 · no usage tracking · no external libraries or fonts loaded by this app.</p>`);}
function renderCatalog(){const query=$('componentSearch').value.toLowerCase().trim();let html='';for(const group of ['Inputs','Processing','Logic','Outputs','Sensors & buses','Networking']){const items=Object.entries(E.defs).filter(([key,d])=>d.group===group&&(prefs.mode==='advanced'||!d.advanced)&&(d.name+' '+d.help+' '+key+' '+Object.values(d.params).map(f=>f.label).join(' ')).toLowerCase().includes(query));if(!items.length)continue;html+=`<details class="component-group" data-group="${esc(group)}" ${query||prefs.catalogOpen?.[group]!==false?'open':''}><summary>${esc(group)} <small>${items.length}</small></summary>`;for(const [key,d] of items)html+=`<button class="component" data-add="${key}" data-color="${d.color}" title="${esc(d.help)}"><span class="glyph" aria-hidden="true">${d.symbol}</span><span>${esc(d.name)}</span><span class="add" aria-hidden="true">+</span></button>`;html+='</details>';} const hidden=Object.values(E.defs).filter(d=>d.advanced&&(d.name+' '+d.help).toLowerCase().includes(query)).length;$('catalog').innerHTML=html||'<p class="catalog-empty">No matching components.</p>';if(prefs.mode!=='advanced'&&query&&hidden)$('catalog').insertAdjacentHTML('beforeend',`<button id="showAdvancedResults" class="catalog-more">${hidden} more in Advanced mode →</button>`);$('catalogCount').textContent=$('catalog').querySelectorAll('[data-add]').length+' components · '+(prefs.mode==='advanced'?'full catalog':'essentials');$('showAdvancedResults')?.addEventListener('click',()=>{prefs.mode='advanced';applyPrefs();render();});for(const el of $('catalog').querySelectorAll('details'))el.ontoggle=()=>{if(query)return;prefs.catalogOpen??={};prefs.catalogOpen[el.dataset.group]=el.open;prefSave();};}
function metadata(n){const p=n.props;switch(n.type){case'clock':return `${p.period} ms · ${p.duty}% duty`;case'button':return p.pin+' · INPUT_PULLUP';case'analog':return p.pin+' · 0–'+E.board(project).adcMax;case'constant':return String(p.value);case'map':return `${p.inMin}…${p.inMax} → ${p.outMin}…${p.outMax}`;case'threshold':return 'Input ≥ '+p.value;case'debounce':return p.delay+' ms stable';case'pulse':return p.duration+' ms · rising edge';case'led':return 'D'+p.pin+(p.activeLow?' · active LOW':' · digital');case'pwm':return 'D'+p.pin+' · 0–255';case'servo':return 'D'+p.pin+' · 0–180°';case'probe':return 'Serial · 115200 baud';default:if(n.type==='bme280'||n.type==='ina219')return n.props.measurement+' · I²C 0x'+Number(p.address).toString(16);if(E.defs[n.type].network)return n.props.topic||n.props.url||n.props.service+' · 0 offline / 1 connected';return E.defs[n.type].i2c?'I²C · 0x'+Number(p.address).toString(16):E.defs[n.type].virtual?'Virtual sensor / hardware driver':E.defs[n.type].out==='number'?'Numeric processing':'Boolean logic';}}
function renderGraph(preserveFocus=true){
 const active=document.activeElement,activeId=active?.dataset?.node,activePort=active?.dataset?.port,activeDir=active?.dataset?.dir;
 $('nodes').innerHTML=project.nodes.map(n=>{const d=E.defs[n.type];return `<div class="node ${d.color} ${selection.has(n.id)||selected===n.id?'selected':''}" data-node="${n.id}" tabindex="0" role="group" aria-label="${esc(n.label)} component"><div class="node-head"><span class="node-symbol" aria-hidden="true">${d.symbol}</span><div><div class="node-title">${esc(n.label)}</div><div class="node-kind">${esc(d.group)} / ${n.id.slice(-4)}</div></div></div><div class="node-meta">${esc(metadata(n))}</div><div class="node-value" data-value="${n.id}"><i></i><span>Ready to preview</span></div>${n.group?`<div class="node-group-label">${esc(n.group)}</div>`:''}<div class="ports"><div class="in-ports">${Object.entries(d.inputs||{}).map(([port,type])=>`<button class="port input ${project.edges.some(e=>e.to===n.id&&e.port===port)?'connected':''} ${pending?.node===n.id&&pending.port===port?'pending':''}" data-node="${n.id}" data-dir="in" data-port="${port}" data-type="${type}" aria-label="${esc(n.label)} ${port} input, ${type}">${port}</button>`).join('')}</div><div class="out-ports">${d.out?`<button class="port output ${project.edges.some(e=>e.from===n.id)?'connected':''} ${pending?.node===n.id&&pending.dir==='out'?'pending':''}" data-node="${n.id}" data-dir="out" data-port="out" data-type="${d.out}" aria-label="${esc(n.label)} output, ${d.out}">${d.out==='boolean'?'bool':'number'}</button>`:''}</div></div></div>`;}).join('');
 for(const n of project.nodes){const el=$('nodes').querySelector(`.node[data-node="${n.id}"]`);el.style.left=n.x+'px';el.style.top=n.y+'px';}
 $('emptyCanvas').hidden=!!project.nodes.length;$('nodeCount').textContent=`${project.nodes.length} COMPONENT${project.nodes.length===1?'':'S'}`;$('footerCount').textContent=project.edges.length+' connection'+(project.edges.length===1?'':'s');
 transform();requestAnimationFrame(drawWires);updateLive();window.EBEditor?.decorate();updateConnectionHint();window.EBPolish?.syncSelection();if(preserveFocus&&activeId&&(activePort||selection.has(activeId))){const q=activePort?`.port[data-node="${activeId}"][data-port="${activePort}"][data-dir="${activeDir}"]`:`.node[data-node="${activeId}"]`;$('nodes').querySelector(q)?.focus({preventScroll:true});}
}
function transform(){const v=project.view;$('world').style.transform=`translate(${v.x}px, ${v.y}px) scale(${v.zoom})`;$('zoomLabel').textContent=Math.round(v.zoom*100)+'%';$('canvas').style.backgroundSize=(20*v.zoom)+'px '+(20*v.zoom)+'px';$('canvas').style.backgroundPosition=`${v.x}px ${v.y}px`;}
function drawWires(){const box=$('canvas').getBoundingClientRect(),v=project.view;let html='';for(const e of project.edges){const source=$('nodes').querySelector(`.port[data-node="${e.from}"][data-dir="out"]`),target=$('nodes').querySelector(`.port[data-node="${e.to}"][data-port="${e.port}"][data-dir="in"]`);if(!source||!target||source.closest('.node').hidden||target.closest('.node').hidden)continue;const a=source.getBoundingClientRect(),b=target.getBoundingClientRect(),x1=(a.right-box.left-v.x)/v.zoom,y1=(a.top+a.height/2-box.top-v.y)/v.zoom,x2=(b.left-box.left-v.x)/v.zoom,y2=(b.top+b.height/2-box.top-v.y)/v.zoom,c=Math.max(45,Math.abs(x2-x1)*.46),path=`M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`;html+=`<path class="wire ${E.defs[node(e.from).type].out==='number'?'number':''} ${selectedEdge===e.id?'selected':''}" d="${path}" data-edge="${e.id}"/><path class="wire-hit" d="${path}" data-edge="${e.id}"/>`;}$('wires').innerHTML=html;}
function fit(){if(!project.nodes.length){project.view={x:0,y:0,zoom:1};transform();mark();return;}const visible=project.nodes.filter(n=>!$('nodes').querySelector(`[data-node="${n.id}"]`)?.hidden),list=visible.length?visible:project.nodes;const rect=$('canvas').getBoundingClientRect(),minX=Math.min(...list.map(n=>n.x)),minY=Math.min(...list.map(n=>n.y)),maxX=Math.max(...list.map(n=>n.x+($('nodes').querySelector(`[data-node="${n.id}"]`)?.offsetWidth||216))),maxY=Math.max(...list.map(n=>n.y+($('nodes').querySelector(`[data-node="${n.id}"]`)?.offsetHeight||180)));const z=Math.max(.25,Math.min(1.15,(rect.width-90)/(maxX-minX),(rect.height-100)/(maxY-minY)));project.view={zoom:z,x:(rect.width-(maxX-minX)*z)/2-minX*z,y:(rect.height-(maxY-minY)*z)/2-minY*z};transform();drawWires();mark();}
function zoom(factor,cx,cy){const r=$('canvas').getBoundingClientRect(),v=project.view,x=cx??r.width/2,y=cy??r.height/2,z=Math.max(.25,Math.min(2,v.zoom*factor));v.x=x-(x-v.x)*z/v.zoom;v.y=y-(y-v.y)*z/v.zoom;v.zoom=z;transform();drawWires();mark();}
function select(id,additive=false){if(additive){if(selection.has(id))selection.delete(id);else selection.add(id);}else selection=new Set(id?[id]:[]);selected=selection.has(id)?id:[...selection].at(-1)||null;selectedEdge=null;renderGraph(false);renderInspector();window.EBPolish?.syncSelection();}
function connect(from,to,port){const a=node(from),b=node(to);if(!a||!b||from===to){say('Choose a different component. Use a sample-delay component for feedback.');return;}if(E.defs[a.type].out!==E.defs[b.type].inputs?.[port]){say('These signal types do not match. Use a conversion component.');return;}const next=E.clone(project);next.edges=next.edges.filter(e=>!(e.to===to&&e.port===port));next.edges.push({id:uid('e'),from,to,port});const cyc=E.validate(next).issues.find(i=>i.message.startsWith('Feedback loops'));if(cyc){say(cyc.message);return;}edit(()=>{project.edges=next.edges;});say('Connection made.');}
function cancelConnection(){pending=null;renderGraph();say('Connection cancelled.');}
function updateConnectionHint(){$('cancelConnection').hidden=!pending;$('canvasHint').textContent=pending?`${node(pending.node)?.label}: choose a ${pending.type} ${pending.dir==='out'?'input':'output'}.`:'Choose an output, then a matching input.';$('canvas').classList.toggle('connecting',!!pending);for(const el of $('nodes').querySelectorAll('.port')){const match=!!pending&&el.dataset.node!==pending.node&&el.dataset.dir!==pending.dir&&el.dataset.type===pending.type;el.classList.toggle('compatible',match);el.classList.toggle('incompatible',!!pending&&!match&&!el.classList.contains('pending'));}}
function portClick(b){const info={node:b.dataset.node,dir:b.dataset.dir,port:b.dataset.port,type:b.dataset.type};if(!pending){pending=info;renderGraph();say('Now select a '+(info.dir==='out'?'matching input.':'matching output.'));return;}if(pending.node===info.node&&pending.port===info.port){pending=null;renderGraph();say('Connection cancelled.');return;}if(pending.dir===info.dir){pending=info;renderGraph();return;}if(pending.type!==info.type){say('Boolean ports connect to Boolean ports; numeric ports connect to numeric ports.');return;}const out=pending.dir==='out'?pending:info,input=pending.dir==='in'?pending:info;connect(out.node,input.node,input.port);}
function add(type){const r=$('canvas').getBoundingClientRect(),v=project.view;edit(()=>{const n=E.makeNode(type,uid('n'),Math.round((r.width*.35-v.x)/v.zoom),Math.round((r.height*.3-v.y)/v.zoom),project.board);let c=0;while(project.nodes.some(a=>Math.abs(a.x-n.x)<35&&Math.abs(a.y-n.y)<35)&&c++<30){n.x+=25;n.y+=25;}project.nodes.push(n);selected=n.id;selection=new Set([n.id]);selectedEdge=null;});if(innerWidth<=900){togglePanel('library',false);$('nodes').querySelector(`.node[data-node="${selected}"]`)?.focus({preventScroll:true});}say('Added '+E.defs[type].name+'. Assign its properties and connections in the inspector.');}
function duplicate(){const ids=new Set(selection.size?selection:[selected]);if(!selected)return;edit(()=>{const map=new Map();const nodes=project.nodes.filter(n=>ids.has(n.id)).map(n=>{const copy=E.clone(n);copy.id=uid('n');map.set(n.id,copy.id);copy.x+=35;copy.y+=35;copy.label+=' copy';return copy;});const edges=project.edges.filter(e=>ids.has(e.from)&&ids.has(e.to)).map(e=>({...e,id:uid('e'),from:map.get(e.from),to:map.get(e.to)}));project.nodes.push(...nodes);project.edges.push(...edges);selection=new Set(nodes.map(n=>n.id));selected=nodes[0]?.id;});say('Selection duplicated with internal connections. Check hardware pins.');}
function removeSelected(){if(selectedEdge){edit(()=>{project.edges=project.edges.filter(e=>e.id!==selectedEdge);selectedEdge=null;});return;}if(!selected)return;edit(()=>{const ids=new Set(selection.size?selection:[selected]);project.nodes=project.nodes.filter(n=>!ids.has(n.id));project.edges=project.edges.filter(e=>!ids.has(e.from)&&!ids.has(e.to));selection.clear();selected=null;});say('Component removed. Undo is available.');}
function hOption(x,key){return esc(key==='pin'?(x.startsWith('A')||E.isESP(project)?x:'D'+x):x);}
function renderInspector(){
 const n=node(selected),edge=project.edges.find(e=>e.id===selectedEdge);
 if(edge){$('inspectorBody').innerHTML=`<span class="tiny-label">SIGNAL CONNECTION</span><h3>${esc(node(edge.from)?.label)} → ${esc(node(edge.to)?.label)}</h3><p>Input: ${esc(edge.port)}. This connection carries program data, not electrical power.</p><button id="deleteEdge" class="danger">Remove connection</button>`;$('deleteEdge').onclick=removeSelected;return;}
 if(!n){$('inspectorBody').innerHTML=`<span class="tiny-label">YOUR INSTRUMENT</span><h3>Make the connection.</h3><p>Select a component to edit its behavior, pins, and connections.</p><hr class="section-divider"><span class="tiny-label">PROJECT NOTES</span><label class="field"><span>Wiring, intent, or reminders</span><textarea id="projectNotes" placeholder="What are you making?">${esc(project.notes)}</textarea></label><p>Notes are saved in your project and included in the printable report.</p>`;$('projectNotes').onchange=e=>edit(()=>project.notes=e.target.value.slice(0,20000));return;}
 const d=E.defs[n.type];let html=`<span class="tiny-label">${esc(d.group.toUpperCase())} / ${esc(n.id.slice(-6))}</span><h3>${esc(d.name)}</h3><p>${esc(d.help)}</p><label class="field"><span>Component name</span><input id="nodeLabel" maxlength="80" value="${esc(n.label)}"></label>`;
 for(const [key,f] of Object.entries(d.params)){const val=n.props[key];if(f.kind==='checkbox')html+=`<label class="field check"><input type="checkbox" data-prop="${key}" ${val?'checked':''}><span>${esc(f.label)}</span></label>`;else if(f.kind==='select')html+=`<label class="field"><span>${esc(f.label)}</span><select data-prop="${key}">${(!E.paramOptions(n.type,key,project).includes(val)?`<option value="${esc(val)}" selected>${esc(val)} · unsupported on this target</option>`:'')}${E.paramOptions(n.type,key,project).map(x=>`<option value="${x}" ${x===val?'selected':''}>${hOption(x,key)}</option>`).join('')}</select></label>`;else if(['text','code'].includes(f.kind))html+=`<label class="field"><span>${esc(f.label)}</span><textarea data-prop="${key}" maxlength="${f.maxLength}" spellcheck="false">${esc(val)}</textarea></label>`;else html+=`<label class="field"><span>${esc(f.label)}</span><input type="number" data-prop="${key}" value="${val}" min="${f.min}" max="${f.max}" step="${f.step}"></label>`;}
 if(d.inputs){html+='<hr class="section-divider"><span class="tiny-label">INPUT CONNECTIONS</span>';for(const [port,type] of Object.entries(d.inputs)){const e=project.edges.find(e=>e.to===n.id&&e.port===port);html+=`<label class="field"><span>${port} · ${type}</span><select data-connect="${port}"><option value="">Not connected</option>${project.nodes.filter(s=>s.id!==n.id&&E.defs[s.type].out===type).map(s=>`<option value="${s.id}" ${e?.from===s.id?'selected':''}>${esc(s.label)} · ${s.id.slice(-4)}</option>`).join('')}</select></label>`;}}
 html+='<div class="inspector-actions"><button id="duplicateNode">Duplicate</button><button id="deleteNode" class="danger">Delete</button></div>';$('inspectorBody').innerHTML=html;
 $('nodeLabel').onchange=e=>{const value=e.target.value.trim();if(value)edit(()=>n.label=value);else renderInspector();};
 $('inspectorBody').querySelectorAll('[data-prop]').forEach(el=>el.onchange=()=>{const key=el.dataset.prop,f=d.params[key];if(!el.checkValidity()){el.reportValidity();return;}const value=f.kind==='number'?Number(el.value):f.kind==='checkbox'?el.checked:el.value;if(f.kind==='number'&&!Number.isFinite(value))return;edit(()=>n.props[key]=value);});
 $('inspectorBody').querySelectorAll('[data-connect]').forEach(el=>el.onchange=()=>{if(el.value)connect(el.value,n.id,el.dataset.connect);else edit(()=>project.edges=project.edges.filter(e=>!(e.to===n.id&&e.port===el.dataset.connect)));renderInspector();});
 $('duplicateNode').onclick=duplicate;$('deleteNode').onclick=removeSelected;
}
function wiringHTML(){const b=E.board(project),rows=project.nodes.filter(n=>n.props.pin).map(n=>[n.label,hOption(n.props.pin,'pin'),E.defs[n.type].name+(n.type==='button'?' · button to GND':'')+(n.type==='led'&&n.props.activeLow?' · active LOW':'')]);if(project.nodes.some(n=>E.defs[n.type].i2c))rows.push(['I²C shared bus',`SDA ${b.i2c[0]} / SCL ${b.i2c[1]}`,project.nodes.filter(n=>E.defs[n.type].i2c).map(n=>n.label+' @ 0x'+Number(n.props.address).toString(16)).join('; ')]);if(project.nodes.some(n=>E.defs[n.type].spi))rows.push(['SPI shared bus',E.isESP(project)?`SCK ${b.spi[0]} / MISO ${b.spi[1]} / MOSI ${b.spi[2]}`:project.board==='mega-2560'?'SCK 52 / MISO 50 / MOSI 51':'SCK 13 / MISO 12 / MOSI 11','MAX31855 uses SCK, MISO and its chip-select pin']);for(const n of project.nodes.filter(n=>n.type==='uart')){const pins=E.isESP(project)?['16','17']:{'1':['19','18'],'2':['17','16'],'3':['15','14']}[n.props.port]||['?','?'];rows.push([n.label,`RX ${pins[0]} / TX ${pins[1]}`,`UART ${n.props.port} · ${n.props.baud} baud`]);}return(rows.length?'<table><thead><tr><th>Component</th><th>Pin / bus</th><th>Function</th></tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>').join('')+'</tbody></table>':'<p>No hardware pins assigned yet.</p>')+`<p>${esc(b.name)} logic: ${b.voltage} V. External LED: include a current-limiting resistor. Servo: suitable separate supply and common GND. Check sensor-module voltage and I²C pull-ups. Pin assignments do not verify the electrical circuit.</p>`;}

function renderChecks(){const result=E.validate(project);const errors=result.issues.filter(i=>i.severity==='error');$('previewBlocked').hidden=!!project.nodes.length&&!errors.length;$('previewBlockedText').textContent=!project.nodes.length?'Add a component or choose a starter to begin.':`${errors.length} ${errors.length===1?'issue needs':'issues need'} attention before preview or firmware export.`;$('previewRepair').textContent=project.nodes.length?'Review checks':'Choose a starter';const reason=errors.length?'Resolve '+errors.length+' issues in Checks.':!project.nodes.length?'Add components to begin.':'Preview uses virtual inputs.';$('run').title=reason;$('exportFirmware').title=errors.length||!project.nodes.length?reason:'Download the Arduino sketch for the selected board.';$('checkCount').textContent=result.issues.filter(i=>i.severity==='error').length;$('checks').innerHTML=result.issues.length?result.issues.map(i=>`<div class="finding ${i.severity}"><strong>${i.severity}</strong><span>${esc(i.message)} <small>Confidence: ${i.confidence}</small></span>${i.node?`<button data-find="${i.node}">Inspect</button>`:''}</div>`).join(''):'<div class="finding"><strong>PASS</strong><span>Signal types, required inputs, pin assignments, and known timer conflicts passed. Hardware behavior still needs testing on your board.</span></div>';$('checks').querySelectorAll('[data-find]').forEach(b=>b.onclick=()=>{select(b.dataset.find);prefs.inspector=true;applyPrefs();});const allowed=result.valid&&project.nodes.length>0;$('run').disabled=!allowed;$('step').disabled=!allowed;$('exportFirmware').disabled=!allowed;$('downloadCode').disabled=!allowed;$('copyCode').disabled=!allowed;try{$('code').textContent=E.generate(project);}catch{$('code').textContent='Complete the program and resolve errors in Checks to generate Arduino code.';}$('wiring').innerHTML=wiringHTML();}
function renderPreview(){
 const virtual=project.nodes.filter(n=>['button','analog'].includes(n.type)||E.defs[n.type].virtual);
 $('inputs').innerHTML=virtual.length?virtual.map(n=>`<div class="input-control">${n.type==='button'?`<label>${esc(n.label)} · D${n.props.pin}</label><button data-button="${n.id}" aria-pressed="${!!simInputs[n.id]}">${simInputs[n.id]?'● Pressed':'○ Released'}</button>`:`<label for="input-${n.id}">${esc(n.label)} <output id="raw-${n.id}">${simInputs[n.id]??E.virtual(n)?.value??Math.round(E.board(project).adcMax/2)}</output></label><input id="input-${n.id}" type="range" data-analog="${n.id}" min="${E.virtual(n)?.min??0}" max="${E.virtual(n)?.max??E.board(project).adcMax}" step="${E.virtual(n)?.step??1}" value="${simInputs[n.id]??E.virtual(n)?.value??Math.round(E.board(project).adcMax/2)}">`}</div>`).join(''):'';
 $('inputs').querySelectorAll('[data-button]').forEach(b=>b.onclick=()=>{const id=b.dataset.button;simInputs[id]=!simInputs[id];b.setAttribute('aria-pressed',String(simInputs[id]));b.textContent=simInputs[id]?'● Pressed':'○ Released';if(sim)sim.input[id]=simInputs[id];window.EBProjectTools?.recordInput(id,simInputs[id],simTime);say('Virtual button '+(simInputs[id]?'pressed.':'released.'));});
 $('inputs').querySelectorAll('[data-analog]').forEach(el=>el.oninput=()=>{simInputs[el.dataset.analog]=Number(el.value);$('raw-'+el.dataset.analog).textContent=el.value;if(sim)sim.input[el.dataset.analog]=Number(el.value);window.EBProjectTools?.recordInput(el.dataset.analog,Number(el.value),simTime);});
 $('outputs').innerHTML=project.nodes.filter(n=>!E.defs[n.type].out||E.defs[n.type].effect).map(n=>`<div class="output-card" data-output="${n.id}"><span>${esc(n.label)}</span><strong>—</strong></div>`).join('');
 if(!node(watch))watch=project.nodes.find(n=>!E.defs[n.type].out)?.id||project.nodes[0]?.id||'';
 $('watchNode').innerHTML=project.nodes.map(n=>`<option value="${n.id}" ${watch===n.id?'selected':''}>${esc(n.label)}</option>`).join('');updateLive();
}
function ensureSim(){if(sim)return true;try{sim=E.createSimulation(project);Object.assign(sim.input,simInputs);sim.tick(0);return true;}catch(e){say(e.message);setTab('checks');return false;}}
function tick(){simTime+=10;sim.tick(simTime);if(simTime%50===0){samples.push({t:simTime,v:typeof sim.values[watch]==='boolean'?Number(sim.values[watch]):sim.values[watch]});if(samples.length>121)samples.shift();}}
function updateLive(){
 $('simTime').textContent=(simTime/1000).toFixed(3)+' s';for(const n of project.nodes){const val=sim?.values[n.id],el=$('nodes').querySelector(`[data-value="${n.id}"]`);if(el){el.querySelector('span').textContent=sim?(fmt(val)+(n.type==='servo'?'° commanded':'')):'Ready to preview';el.querySelector('i').classList.toggle('on',sim&&!!val);}}
 $('outputs').querySelectorAll('[data-output]').forEach(el=>{const n=node(el.dataset.output),value=sim?.values[n.id];el.querySelector('strong').textContent=sim?fmt(value)+(n.type==='servo'?'°':''):'—';el.classList.toggle('on',!!value);});
 $('watchValue').textContent=sim?fmt(sim.values[watch]):'—';drawScope();
}
function drawScope(){let html='<path d="M0 15H600 M0 47H600 M0 80H600" fill="none" stroke="var(--line)" stroke-width=".6"/>';const valid=samples.filter(s=>Number.isFinite(s.v));if(valid.length){let low=Math.min(...valid.map(s=>s.v)),high=Math.max(...valid.map(s=>s.v));if(low===high){low=Math.min(0,low);high=Math.max(1,high);}const range=high-low||1,start=Math.max(0,simTime-6000);let path='',gap=true;for(const s of samples){if(!Number.isFinite(s.v)){gap=true;continue;}path+=`${gap?'M':'L'}${((s.t-start)/6000*600).toFixed(1)} ${(82-(s.v-low)/range*68).toFixed(1)} `;gap=false;}html+=`<path d="${path}" fill="none" stroke="var(--accent)" stroke-width="2" vector-effect="non-scaling-stroke"/>`;}$('scope').innerHTML=html;}

function frame(time){if(running&&sim){if(!lastFrame)lastFrame=time;accumulator+=Math.min(time-lastFrame,200);lastFrame=time;while(accumulator>=10){tick();accumulator-=10;}if(time-lastPaint>60){updateLive();lastPaint=time;}}requestAnimationFrame(frame);}
function setTab(name){tab=name;document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});document.querySelectorAll('[role=tabpanel]').forEach(el=>el.hidden=el.id!=='tab-'+name);if(!prefs.dock){prefs.dock=true;applyPrefs();}}
function togglePanel(kind,open){prefs[kind]=open;if(open&&innerWidth<=900)prefs[kind==='library'?'inspector':'library']=false;applyPrefs();if(open)(kind==='library'?$('componentSearch'):$('inspectorBody').querySelector('input,textarea,select,button')||$('hideInspector')).focus();}
function applyPrefs(){if(prefs.dockHeight)$('dock').style.height=prefs.dock?prefs.dockHeight+'px':'42px';document.documentElement.dataset.theme=['dark','light','contrast'].includes(prefs.theme)?prefs.theme:'dark';$('library').hidden=!prefs.library;$('library').classList.remove('mobile-hidden');$('showLibrary').hidden=!!prefs.library;$('inspector').hidden=!prefs.inspector;$('inspector').classList.remove('mobile-hidden');$('dock').classList.toggle('collapsed',!prefs.dock);$('toggleDock').textContent=prefs.dock?'⌄':'⌃';$('toggleDock').setAttribute('aria-label',prefs.dock?'Collapse lower panel':'Expand lower panel');prefSave();window.EBPolish?.syncPanels();requestAnimationFrame(drawWires);}
function render(){ renderCatalog(); selection=new Set([...selection].filter(id=>node(id)));if(selected&&!selection.size)selection.add(selected); $('projectName').value=project.name;renderGraph();renderInspector();renderChecks();renderPreview();$('undo').disabled=!history.length;$('redo').disabled=!future.length;window.EBStudio?.refresh();window.EBProjectTools?.refresh();window.EBEditor?.decorate();}
function undo(){if(!history.length)return;future.push(E.clone(project));project=history.pop();selection.clear();selected=null;selectedEdge=null;pending=null;stopPreview(true);render();mark();say('Undone.');}
function redo(){if(!future.length)return;history.push(E.clone(project));project=future.pop();selection.clear();selected=null;selectedEdge=null;pending=null;stopPreview(true);render();mark();say('Redone.');}
function download(text,name,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function filename(){return project.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'electronbench-project';}
function firmware(){try{download(E.generate(project),'electronbench_project.ino','text/x-arduino');say(E.network.used(project)?'Sketch downloaded. Add electronbench_secrets.h from Network settings beside it, or export a project bundle with its empty template.':'Arduino sketch downloaded. Open it in Arduino IDE; select the matching board, then upload.');}catch(e){say(e.message);setTab('checks');}}
function printReport(){let area=$('printArea');if(!area){area=document.createElement('section');area.id='printArea';area.hidden=true;document.body.append(area);}let code='';try{code=E.generate(project);}catch{code='Firmware unavailable: resolve the program errors.';}area.innerHTML=`<h1>ELECTRONBENCH · ${esc(project.name)}</h1><p>Project report · v${E.VERSION} · ${new Date().toLocaleString()}<br>Target: ${esc(E.board(project).name)} · ${esc(E.fqbn(project))}</p><h2>Project notes</h2><p>${esc(project.notes||'No notes recorded.').replace(/\n/g,'<br>')}</p><h2>Pin assignments</h2>${wiringHTML()}<h2>Signal connections</h2><table><thead><tr><th>Source</th><th>Destination</th><th>Input</th></tr></thead><tbody>${project.edges.map(e=>`<tr><td>${esc(node(e.from)?.label)}</td><td>${esc(node(e.to)?.label)}</td><td>${esc(e.port)}</td></tr>`).join('')}</tbody></table><h2>Checks</h2><p>${E.validate(project).issues.map(i=>esc(i.severity.toUpperCase()+': '+i.message)).join('<br>')||'Static checks passed.'}</p><p>Static checks and behavioral preview do not establish electrical correctness or hardware validation. Preview time: ${(simTime/1000).toFixed(3)} s. Hardware observations are user-recorded below; no automatic certification is implied.</p><h2>Evidence</h2>${project.evidence.map(e=>`<p><strong>${esc(e.kind)}</strong> · ${esc(e.date)}<br>${esc(e.note)}</p>`).join('')||'<p>No evidence recorded.</p>'}<h2>Assumptions</h2>${project.assumptions.map(e=>`<p>${esc(e.note)} · ${esc(e.date)}</p>`).join('')||'<p>No assumptions recorded.</p>'}<h2>Build dependencies</h2><pre>${esc(E.buildProfile(project))}</pre><h2>Generated Arduino firmware</h2><pre>${esc(code)}</pre>`;window.print();}
function setTool(value){tool=value;$('canvas').classList.toggle('pan',tool==='pan');for(const k of ['select','pan']){$(k+'Tool').classList.toggle('active',k===tool);$(k+'Tool').setAttribute('aria-pressed',k===tool);}}
let space=false;
$('canvas').addEventListener('pointerdown',ev=>{
 if(ev.target.closest('.port')||ev.target.closest('.canvas-bottom')||ev.target.closest('#emptyCanvas'))return;
 const e=ev.target.closest('[data-edge]');if(e){selectedEdge=e.dataset.edge;selected=null;selection.clear();renderGraph(false);renderInspector();return;}
 const nEl=ev.target.closest('.node');if(nEl&&ev.button===0&&!space&&tool!=='pan'){ev.preventDefault();const n=node(nEl.dataset.node);select(n.id,ev.shiftKey||ev.ctrlKey||ev.metaKey);if(selection.has(n.id))$('nodes').querySelector(`.node[data-node="${n.id}"]`)?.focus({preventScroll:true});if(ev.target.closest('.node-head')){drag={kind:'node',id:n.id,startX:ev.clientX,startY:ev.clientY,x:n.x,y:n.y,changed:false,before:E.clone(project),positions:project.nodes.filter(a=>selection.has(a.id)).map(a=>({id:a.id,x:a.x,y:a.y}))};$('canvas').setPointerCapture(ev.pointerId);}return;}
 if(ev.button===1||tool==='pan'||space){ev.preventDefault();drag={kind:'pan',startX:ev.clientX,startY:ev.clientY,x:project.view.x,y:project.view.y};$('canvas').setPointerCapture(ev.pointerId);}else if(ev.button===0){selected=null;selection.clear();selectedEdge=null;pending=null;renderGraph(false);renderInspector();}
});
$('canvas').addEventListener('pointermove',ev=>{if(!drag)return;const dx=ev.clientX-drag.startX,dy=ev.clientY-drag.startY;if(drag.kind==='pan'){project.view.x=drag.x+dx;project.view.y=drag.y+dy;transform();drawWires();}else {if(!drag.changed&&Math.hypot(dx,dy)<3)return;if(!drag.changed){stopPreview(true);drag.changed=true;}const n=node(drag.id);if(!n)return;for(const pos of drag.positions){const m=node(pos.id);m.x=Math.max(-20000,Math.min(20000,Math.round(pos.x+dx/project.view.zoom)));m.y=Math.max(-20000,Math.min(20000,Math.round(pos.y+dy/project.view.zoom)));const el=$('nodes').querySelector(`.node[data-node="${m.id}"]`);el.style.left=m.x+'px';el.style.top=m.y+'px';}drawWires();}});
function finishDrag(){if(!drag)return;if(drag.kind==='node'&&drag.changed){history.push(drag.before);if(history.length>60)history.shift();future=[];render();}if(drag.kind==='pan'||drag.changed)mark();drag=null;}
$('canvas').addEventListener('pointerup',finishDrag);$('canvas').addEventListener('pointercancel',finishDrag);
$('canvas').addEventListener('click',ev=>{const b=ev.target.closest('.port');if(b)portClick(b);});
$('canvas').addEventListener('wheel',ev=>{ev.preventDefault();const r=$('canvas').getBoundingClientRect();zoom(ev.deltaY<0?1.08:1/1.08,ev.clientX-r.left,ev.clientY-r.top);},{passive:false});
$('canvas').addEventListener('contextmenu',ev=>{const n=ev.target.closest('.node');if(!n)return;ev.preventDefault();select(n.dataset.node);const menu=$('contextMenu');menu.hidden=false;menu.style.left=Math.min(innerWidth-205,ev.clientX)+'px';menu.style.top=Math.min(innerHeight-90,ev.clientY)+'px';$('contextDuplicate').focus();});
document.addEventListener('pointerdown',ev=>{if(!ev.target.closest('#contextMenu'))$('contextMenu').hidden=true;});
$('contextDuplicate').onclick=()=>{duplicate();$('contextMenu').hidden=true;};$('contextDelete').onclick=()=>{removeSelected();$('contextMenu').hidden=true;};
document.addEventListener('keydown',ev=>{if(ev.defaultPrevented||$('modal').open)return;const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName);if(ev.key==='Escape'){cancelConnection();$('contextMenu').hidden=true;return;}if(typing)return;if(ev.code==='Space'&&document.activeElement===$('canvas')){space=true;ev.preventDefault();}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?redo():undo();return;}if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='d'){ev.preventDefault();duplicate();return;}if(ev.key==='Delete'||ev.key==='Backspace'){if((selected||selectedEdge)&&$('canvas').contains(document.activeElement)){ev.preventDefault();removeSelected();}return;}const nEl=document.activeElement.closest('.node');if(nEl&&document.activeElement===nEl&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(ev.key)){ev.preventDefault();const id=nEl.dataset.node,n=node(id),delta=ev.shiftKey?20:5;edit(()=>{n.x+=ev.key==='ArrowLeft'?-delta:ev.key==='ArrowRight'?delta:0;n.y+=ev.key==='ArrowUp'?-delta:ev.key==='ArrowDown'?delta:0;});$('nodes').querySelector(`.node[data-node="${id}"]`).focus();}});
document.addEventListener('keyup',ev=>{if(ev.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;finishDrag();});
$('nodes').addEventListener('focusin',ev=>{if(ev.target.classList.contains('node')){selected=ev.target.dataset.node;if(!selection.has(selected))selection=new Set([selected]);selectedEdge=null;document.querySelectorAll('.node').forEach(n=>n.classList.toggle('selected',selection.has(n.dataset.node)));renderInspector();window.EBPolish?.syncSelection();}});
$('catalog').onclick=ev=>{const b=ev.target.closest('[data-add]');if(b)add(b.dataset.add);};$('componentSearch').oninput=renderCatalog;
$('projectName').onchange=ev=>{const text=ev.target.value.trim();if(text)edit(()=>project.name=text);else $('projectName').value=project.name;};
$('newProject').onclick=()=>confirmReplace('Start a fresh project?',()=>replaceProject(E.blank()));$('examples').onclick=showStarters;$('emptyStarter').onclick=showStarters;$('help').onclick=showHelp;$('closeModal').onclick=closeModal;
$('modal').onclick=ev=>{if(ev.target===$('modal')){const r=$('modal').getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)closeModal();}};
$('saveProject').onclick=()=>{download(JSON.stringify(project,null,2),filename()+'.electronbench.json','application/json');say('Portable JSON project downloaded.');};
$('importProject').onclick=()=>$('fileInput').click();$('fileInput').onchange=async ev=>{const f=ev.target.files[0];ev.target.value='';if(!f)return;if(f.size>4000000){say('Project import is limited to 4 MB.');return;}try{const next=E.importProject(JSON.parse(await f.text()));confirmReplace('Open '+next.name+'?',()=>{replaceProject(next);say('Project imported. Review Checks before exporting firmware.');});}catch(e){modal('Could not open this project',`<p>${esc(e.message)}</p><p>Your current project has not changed.</p>`);}};
$('exportFirmware').onclick=firmware;$('downloadCode').onclick=firmware;$('copyCode').onclick=async()=>{try{await navigator.clipboard.writeText(E.generate(project));say('Arduino code copied.');}catch{say('Clipboard is unavailable here. Download the sketch instead.');}};
$('cancelConnection').onclick=cancelConnection;$('previewRepair').onclick=()=>{if(project.nodes.length){setTab('checks');document.querySelector('[data-tab="checks"]').focus();}else showStarters();};$('printReport').onclick=printReport;$('undo').onclick=undo;$('redo').onclick=redo;$('fit').onclick=fit;$('zoomIn').onclick=()=>zoom(1.2);$('zoomOut').onclick=()=>zoom(1/1.2);$('selectTool').onclick=()=>setTool('select');$('panTool').onclick=()=>setTool('pan');
$('theme').onclick=()=>{const themes=['dark','light','contrast'];prefs.theme=themes[(themes.indexOf(prefs.theme)+1)%themes.length];applyPrefs();say(prefs.theme+' theme selected.');};
$('hideLibrary').onclick=()=>{togglePanel('library',false);$('showLibrary').focus();};$('showLibrary').onclick=()=>togglePanel('library',true);$('hideInspector').onclick=()=>{togglePanel('inspector',false);$('inspectToggle').focus();};$('inspectToggle').onclick=()=>togglePanel('inspector',!prefs.inspector);$('toggleDock').onclick=()=>{prefs.dock=!prefs.dock;applyPrefs();};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('run').onclick=()=>{if(running){stopPreview();say('Preview paused.');return;}if(!ensureSim())return;running=true;lastFrame=0;$('run').textContent='Ⅱ Pause';$('modeBadge').textContent='PREVIEW';$('modeBadge').classList.add('running');say('Behavioral preview running. Outputs are virtual.');};
$('step').onclick=()=>{stopPreview();if(ensureSim()){tick();updateLive();say('Advanced preview by 10 ms.');}};
$('reset').onclick=()=>{stopPreview(true);if(project.nodes.length&&E.validate(project).valid){ensureSim();updateLive();}say('Preview reset to zero.');};
$('watchNode').onchange=ev=>{watch=ev.target.value;samples=[];updateLive();};
window.addEventListener('resize',()=>requestAnimationFrame(drawWires));document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stopPreview();say('Preview paused while the tab is hidden.');}});window.addEventListener('pagehide',()=>{if(dirty)save();});window.addEventListener('beforeunload',e=>{if(dirty)save();if(dirty){e.preventDefault();e.returnValue='';}});
if(innerWidth<600)prefs.library=false;applyPrefs();renderCatalog();render();requestAnimationFrame(()=>{if(!localStorageAvailable()){$('saveState').textContent='● Storage unavailable — save JSON';$('saveState').classList.add('error');}else if(!recoveryRaw){if(!restoredView)fit();save();}});requestAnimationFrame(frame);
function localStorageAvailable(){try{localStorage.getItem(KEY);return true;}catch{return false;}}
if(recoveryRaw){modal('Recover your workspace','<p>The saved workspace could not be read. Its original data has been kept. Download it before starting over, or restore the previous autosave.</p><div class="modal-actions"><button id="downloadRecovery">Download saved data</button><button id="restoreRecovery">Restore previous</button><button id="clearRecovery">Start fresh</button></div>');$('downloadRecovery').onclick=()=>download(recoveryRaw,'electronbench-recovery.txt');$('restoreRecovery').onclick=()=>{try{const p=E.importProject(JSON.parse(localStorage.getItem(BACKUP)));recoveryRaw=null;replaceProject(p);closeModal();}catch{say('The previous autosave is also unavailable. Download the saved data before starting fresh.');}};$('clearRecovery').onclick=()=>{recoveryRaw=null;replaceProject(E.blank());closeModal();};}
window.EBApp={get project(){return project;},get tab(){return tab;},get pending(){return pending;},togglePanel,cancelConnection,drawWires,duplicate,removeSelected,get selected(){return selected;},get selection(){return new Set(selection);},get simTime(){return simTime;},get sim(){return sim;},get inputs(){return simInputs;},get prefs(){return prefs;},get history(){return history;},edit,render,select,replaceProject,modal,closeModal,say,download,esc,uid,fit,setTab,applyPrefs,stopPreview,ensureSim,updateLive,mark,save,showStarters,firmware,renderChecks,focusNode(id){const n=node(id);if(!n)return;const scope=$('diagramScope');if(scope&&scope.value&&scope.value!==n.group){scope.value='';scope.dispatchEvent(new Event('change'));}select(id);project.view.x=80-n.x*project.view.zoom;project.view.y=60-n.y*project.view.zoom;transform();drawWires();mark();$('nodes').querySelector(`.node[data-node="${id}"]`)?.focus();},getPrevious(){return E.importProject(JSON.parse(localStorage.getItem(BACKUP)));}};
window.dispatchEvent(new CustomEvent('eb:ready'));
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>$('offlineState').textContent='· offline cache ready').catch(()=>$('offlineState').textContent='· offline cache unavailable');
})();
