/* ELECTRONBENCH network configuration and targeted examples. GPL-3.0-only. */
(()=>{'use strict';const A=window.EBApp,E=window.EB,N=E.network,$=id=>document.getElementById(id),h=A.esc;let privateValues={wifiPassword:'',mqttUsername:'',mqttPassword:'',httpBearer:''},revision=0;
function settings(){const n=N.normalize(A.project.network);A.modal('Network settings',`<p>ESP32 firmware makes the requests. Browser preview stays local and uses virtual readings. Network connected nodes let you rehearse disconnection.</p><div class="network-fields"><label class="field"><span>Wi-Fi SSID</span><input id="net-ssid" maxlength="32" value="${h(n.ssid)}"></label><label class="field"><span>MQTT broker hostname / IPv4</span><input id="net-mqttHost" maxlength="253" value="${h(n.mqttHost)}"></label><label class="field"><span>MQTT port</span><input id="net-mqttPort" type="number" min="1" max="65535" value="${n.mqttPort}"></label><label class="field check"><input id="net-mqttTLS" type="checkbox" ${n.mqttTLS?'checked':''}><span>MQTT over TLS (usually port 8883)</span></label><label class="field"><span>Client ID prefix · device ID is appended</span><input id="net-clientPrefix" maxlength="32" value="${h(n.clientPrefix)}"></label><label class="field"><span>Reconnect interval · ms</span><input id="net-retryMs" type="number" min="1000" max="60000" step="1" value="${n.retryMs}"></label><label class="field"><span>Socket timeout · ms</span><input id="net-timeoutMs" type="number" min="500" max="5000" step="1" value="${n.timeoutMs}"></label><label class="field"><span>Time server for TLS</span><input id="net-ntpHost" maxlength="253" value="${h(n.ntpHost)}"></label></div><label class="field"><span>Trusted root CA · PEM, required for TLS / HTTPS</span><textarea id="net-rootCA" maxlength="16000" spellcheck="false">${h(n.rootCA)}</textarea></label><p>TLS validates certificates after the board synchronizes time. HTTP and plain MQTT are suitable only for a trusted network. Network operations run on a separate task; responses arrive asynchronously.</p><h3>Private build credentials</h3><p>These fields last only while this page is open. They are excluded from autosave, project JSON, reports, and project bundles. A filled secrets header and firmware binary contain credentials; keep them private.</p><div class="network-fields">${Object.entries({wifiPassword:'Wi-Fi password (empty for open Wi-Fi)',mqttUsername:'MQTT username',mqttPassword:'MQTT password',httpBearer:'HTTP Bearer token (optional; HTTPS only)'}).map(([k,label])=>`<label class="field"><span>${label}</span><input id="private-${k}" type="password" autocomplete="off" maxlength="${k==='httpBearer'?512:128}" value="${h(privateValues[k])}"></label>`).join('')}</div><div class="modal-actions"><button id="saveNetwork" class="primary">Save settings for this project</button><button id="downloadSecrets">Download private secrets header</button><button id="clearSecrets">Forget credentials</button></div><p id="networkMessage" role="status"></p><p>Put <code>electronbench_secrets.h</code> beside the generated sketch when compiling manually. The local companion supplies this file automatically from the current session. Project bundles contain an empty template.</p>`);
function capture(){const cfg={};for(const k of Object.keys(n)){const field=$('net-'+k);if(!field.checkValidity()){field.reportValidity();throw Error('Correct the highlighted setting.');}cfg[k]=typeof n[k]==='boolean'?field.checked:typeof n[k]==='number'?Number(field.value):field.value;}const next=N.normalize(cfg),secret=Object.fromEntries(Object.keys(privateValues).map(k=>[k,$('private-'+k).value]));N.secretsHeader(secret);return{next,secret};}
$('saveNetwork').onclick=()=>{try{const {next,secret}=capture();A.edit(()=>A.project.network=next);privateValues=secret;revision++;$('networkMessage').textContent='Network settings saved. Credentials remain in this page session. Review Checks for missing or incompatible settings.';}catch(e){$('networkMessage').textContent=e.message;}};
$('downloadSecrets').onclick=()=>{try{const {secret}=capture();A.download(N.secretsHeader(secret),'electronbench_secrets.h','text/x-c');$('networkMessage').textContent='Private header downloaded. Keep it out of repositories and shared bundles.';}catch(e){$('networkMessage').textContent=e.message;}};
$('clearSecrets').onclick=()=>{privateValues={wifiPassword:'',mqttUsername:'',mqttPassword:'',httpBearer:''};revision++;for(const k of Object.keys(privateValues))$('private-'+k).value='';$('networkMessage').textContent='Session credentials cleared. Exported headers or flashed firmware are unchanged.';};}
function example(kind,board){const p=E.blank();p.board=kind==='mqtt'||kind==='http'?(E.isESP(board)?board:'esp32-devkitc'):board;let id=0,edge=0;const add=(type,props={},label)=>{const n=E.makeNode(type,'n'+(++id),60+Math.floor((id-1)/3)*270,80+((id-1)%3)*200,p.board);Object.assign(n.props,props);if(label)n.label=label;p.nodes.push(n);return n;},link=(a,b)=>p.edges.push({id:'e'+(++edge),from:a.id,to:b.id,port:'in'});p.settings.telemetry=true;
if(kind==='environment'){p.name='Environment on the bench';for(const [measurement,label]of [['temperature','Temperature °C'],['humidity','Humidity %'],['pressure','Pressure hPa']]){const sensor=add('bme280',{measurement},label);link(sensor,add('probe',{},label+' serial'));}p.notes='BME280, not BMP280. One device at 0x76; three nodes share its driver. Match module supply and I²C pull-ups to board logic voltage.';}
if(kind==='power'){p.name='Power on the bench';for(const [measurement,label]of [['voltage','Bus V'],['current','Current mA'],['power','Power mW']]){const sensor=add('ina219',{measurement},label);link(sensor,add('probe',{},label+' serial'));}p.notes='INA219 at 0x40 with 0.1 Ω shunt, 32 V / 2 A library calibration. Respect the device 26 V input limit and breakout shunt rating. Shared ground; not mains isolated.';}
if(kind==='mqtt'){p.name='MQTT sensor and command';p.network={...N.defaults(),ssid:'YOUR_WIFI_SSID',mqttHost:'192.168.1.10'};const sensor=add('bme280'),pub=add('mqttPublish',{topic:'electronbench/temperature'});link(sensor,pub);const sub=add('mqttSubscribe',{topic:'electronbench/command'}),pwm=add('pwm',{pin:p.board==='esp32-devkitc'?'25':'4'});link(sub,pwm);add('networkStatus',{service:'wifi'},'Wi-Fi connected');add('networkStatus',{service:'mqtt'},'MQTT connected');link(sub,add('probe'));p.notes='Set your SSID, broker, and session credentials in Network settings. Input topic is a plain number 0–255; stale commands become NaN and PWM goes to zero. Preview sliders model messages and connection state.';}
if(kind==='http'){p.name='HTTP numeric exchange';p.network={...N.defaults(),ssid:'YOUR_WIFI_SSID'};const value=add('constant',{value:22.5}),post=add('httpPost');link(value,post);const get=add('httpGet');link(get,add('probe'));add('networkStatus',{service:'wifi'});p.notes='Replace the GET/POST URLs with your own endpoints. POST sends text/plain; GET expects a plain numeric body of at most 64 bytes. HTTP is unencrypted; choose HTTPS and add a root CA for private data.';}
return p;}
function extendStarters(){const grid=$('starterGrid');for(const [kind,title,description]of [['environment','BME280 environment','Temperature, humidity, and pressure from one shared sensor.'],['power','INA219 power monitor','Voltage, current, and power with explicit units.'],['mqtt','ESP32 MQTT exchange','Sensor publishing, numeric commands, and connection status.'],['http','ESP32 HTTP exchange','Plain-number GET and POST with status and failure handling.']]){const b=document.createElement('button');b.className='starter';b.dataset.extraStarter=kind;b.innerHTML=`<span class="starter-icon">${kind==='environment'?'RH':kind==='power'?'V·A':'↔'}</span><span><strong>${title}</strong><small>${description}</small></span>`;b.onclick=()=>{A.replaceProject(example(kind,A.project.board));A.closeModal();A.say('Starter opened. Inspect wiring and configuration; preview values are virtual.');};grid.append(b);}}
window.EBNetworkUI={settings,example,extendStarters,secrets:()=>({...privateValues}),get revision(){return revision;}};
})();
