/* ELECTRONBENCH ESP32 networking generator and behavioral model. GPL-3.0-only. */
(function(root){'use strict';
const types=new Set(['networkStatus','mqttSubscribe','mqttPublish','httpGet','httpPost']);
const defaults=()=>({ssid:'',mqttHost:'',mqttPort:1883,mqttTLS:false,clientPrefix:'electronbench',rootCA:'',ntpHost:'pool.ntp.org',retryMs:10000,timeoutMs:2000});
function normalize(value){const out=defaults();if(value===undefined)return out;if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid network configuration.');for(const [key,max]of Object.entries({ssid:32,mqttHost:253,clientPrefix:32,rootCA:16000,ntpHost:253})){if(value[key]!==undefined){if(typeof value[key]!=='string'||value[key].length>max||value[key].includes('\0'))throw Error('Invalid network '+key);out[key]=value[key];}}for(const [key,min,max]of [['mqttPort',1,65535],['retryMs',1000,60000],['timeoutMs',500,5000]])if(value[key]!==undefined){if(!Number.isInteger(value[key])||value[key]<min||value[key]>max)throw Error('Invalid network '+key);out[key]=value[key];}out.mqttTLS=value.mqttTLS===true;return out;}
function definitions({param,pin,bool,text}){const base={group:'Networking',color:'amber',out:'number',advanced:true,network:true};return{
 networkStatus:{...base,name:'Network connected',symbol:'⌁',virtual:{min:0,max:1,step:1,value:1},help:'1 when Wi-Fi or MQTT is connected, otherwise 0. Preview sliders on these nodes also control virtual connection state for other network components.',params:{service:pin('Connection','wifi',['wifi','mqtt'])}},
 mqttSubscribe:{...base,name:'MQTT number input',symbol:'↓M',virtual:{min:-1000,max:1000,step:.1,value:0},help:'Subscribe to one exact topic with a numeric payload. Invalid, disconnected, or stale readings become NaN. Preview slider changes represent incoming messages.',params:{topic:text('Topic','electronbench/input',160),staleMs:param('Stale after · ms',10000,1000,3600000)}},
 mqttPublish:{...base,name:'MQTT number output',symbol:'↑M',effect:true,inputs:{in:'number'},help:'Publish a numeric input at an interval, QoS 0. Output is 1 after the last successful send, otherwise 0. Retain is optional.',params:{topic:text('Topic','electronbench/output',160),interval:param('Publish interval · ms',1000,500,3600000),retain:bool('Retain last value at broker',false)}},
 httpGet:{...base,name:'HTTP GET number',symbol:'↓H',virtual:{min:-1000,max:1000,step:.1,value:0},help:'GET a plain-text numeric response, or return the HTTP status. Numeric bodies are limited to 64 bytes. Failure or a non-numeric body produces NaN in number mode.',params:{url:text('HTTP / HTTPS URL','http://192.168.1.10/value',500),result:pin('Output','number',['number','status']),interval:param('Request interval · ms',5000,1000,3600000)}},
 httpPost:{...base,name:'HTTP POST number',symbol:'↑H',effect:true,inputs:{in:'number'},help:'POST the input as text/plain at an interval. Output is the HTTP status; negative values indicate failure. Invalid input skips the request. No automatic retry of a failed POST within its interval.',params:{url:text('HTTP / HTTPS URL','http://192.168.1.10/value',500),interval:param('Request interval · ms',5000,1000,3600000)}}};}
const used=p=>p.nodes.some(n=>types.has(n.type));
const usesMQTT=p=>p.nodes.some(n=>n.type.startsWith('mqtt')||(n.type==='networkStatus'&&n.props.service==='mqtt'));
function issues(p,isESP){if(!used(p))return[];const out=[],net=normalize(p.network),add=(severity,node,message)=>out.push({severity,node,message,confidence:'High'});if(!isESP)add('error',null,'Network components require an ESP32 target.');if(!net.ssid.trim())add('error',null,'Wi-Fi SSID is required in Network settings.');const tls=net.mqttTLS&&usesMQTT(p)||p.nodes.some(n=>/^https:/.test(n.props.url||''));if(tls&&(!net.rootCA.includes('-----BEGIN CERTIFICATE-----')||!net.rootCA.includes('-----END CERTIFICATE-----')))add('error',null,'TLS connections require a PEM root CA certificate in Network settings.');if(tls&&!/^[a-zA-Z0-9.-]+$/.test(net.ntpHost))add('error',null,'TLS requires a valid time-server hostname.');if(usesMQTT(p)&&(!/^[a-zA-Z0-9.-]+$/.test(net.mqttHost)||!net.mqttHost))add('error',null,'MQTT broker hostname or IPv4 address is required.');if(!/^[a-zA-Z0-9_-]{1,32}$/.test(net.clientPrefix))add('error',null,'MQTT client prefix must use letters, numbers, hyphens, or underscores.');if(usesMQTT(p)&&!net.mqttTLS)add('warning',null,'MQTT uses unencrypted TCP. Use a trusted LAN or enable TLS.');const status=new Set();for(const n of p.nodes){if(n.type==='networkStatus'){if(status.has(n.props.service))add('error',n.id,'Use one Network connected node per service so the preview has one connection-state control.');status.add(n.props.service);}if(n.type.startsWith('mqtt')&&(!n.props.topic.trim()||new TextEncoder().encode(n.props.topic).length>160||/[+#\0-\x1f]/.test(n.props.topic)))add('error',n.id,'MQTT topics must be exact topics up to 160 UTF-8 bytes, without wildcards or control characters.');if(n.type.startsWith('http')){let url;try{url=new URL(n.props.url);}catch{}if(!/^https?:\/\//.test(n.props.url)||/[\x00-\x20]/.test(n.props.url)||!url||!['http:','https:'].includes(url.protocol)||url.username||url.password||url.hash)add('error',n.id,'HTTP URL must use http:// or https:// without embedded credentials or fragments.');else if(url.protocol==='http:')add('warning',n.id,'HTTP is unencrypted. Use a trusted LAN or HTTPS with a root CA.');}}if(p.nodes.filter(n=>n.type.startsWith('http')).length>4)add('error',null,'Use at most four HTTP components per project.');if(p.nodes.filter(n=>types.has(n.type)).length>32)add('error',null,'Use at most 32 network components per project.');add('info',null,'Network preview uses virtual readings. Generated firmware performs the real requests; credentials are provided separately.');return out;}
function inputs(){const versions={};const value={};Object.defineProperty(value,'__versions',{value:versions});return new Proxy(value,{set(obj,key,v){obj[key]=v;if(typeof key==='string')versions[key]=(versions[key]||0)+1;return true;}});}
function simulate(p,n,st,read,now,input){const connected=service=>{const status=p.nodes.find(x=>x.type==='networkStatus'&&x.props.service===service);return !status||Number(input[status.id]??1)===1;},wifi=connected('wifi'),mqtt=wifi&&connected('mqtt');if(n.type==='networkStatus')return(n.props.service==='wifi'?wifi:mqtt)?1:0;if(n.type==='mqttSubscribe'){const rev=input.__versions?.[n.id]||0;if(st.rev!==rev){st.rev=rev;st.messageAt=now;}return mqtt&&now-st.messageAt<n.props.staleMs?(input[n.id]===null?NaN:input[n.id]??0):NaN;}if(!st.networkInit||now-st.at>=n.props.interval){st.networkInit=true;st.at=now;if(n.type==='mqttPublish')st.networkValue=mqtt&&Number.isFinite(read('in'))?1:0;else if(n.type==='httpPost')st.networkValue=!wifi?-1000:Number.isFinite(read('in'))?200:-1001;else st.networkValue=!wifi?(n.props.result==='status'?-1000:NaN):n.props.result==='status'?200:input[n.id]===null?NaN:input[n.id]??0;}if(n.type==='mqttPublish'&&!mqtt)return 0;return st.networkValue;}
function secretsHeader(secrets={}){const values={};for(const [key,max]of Object.entries({wifiPassword:128,mqttUsername:128,mqttPassword:128,httpBearer:512})){const v=secrets[key]??'';if(typeof v!=='string'||v.length>max||/[\0\r\n]/.test(v))throw Error('Invalid credential field: '+key);values[key]=v;}return '// Private firmware configuration. Do not commit or share filled credentials.\n#pragma once\n'+Object.entries({EB_WIFI_PASSWORD:values.wifiPassword,EB_MQTT_USERNAME:values.mqttUsername,EB_MQTT_PASSWORD:values.mqttPassword,EB_HTTP_BEARER:values.httpBearer}).map(([k,v])=>'#define '+k+' '+JSON.stringify(v)).join('\n')+'\n';}
function generate(p,ix){if(!used(p))return{includes:[],globals:[],setup:[],node:()=>''};const cfg=normalize(p.network),nodes=p.nodes.filter(n=>types.has(n.type)),slot=new Map(nodes.map((n,i)=>[n.id,i])),mqtt=usesMQTT(p),http=nodes.some(n=>n.type.startsWith('http')),tls=(mqtt&&cfg.mqttTLS)||nodes.some(n=>/^https:/.test(n.props.url||'')),q=JSON.stringify,sub=nodes.filter(n=>n.type==='mqttSubscribe');const includes=['#include <freertos/FreeRTOS.h>','#include <freertos/task.h>','#include <freertos/queue.h>','#include <WiFi.h>','#include <stdlib.h>','#include <string.h>','#include <ctype.h>','#include "electronbench_secrets.h"',...(tls?['#include <WiFiClientSecure.h>','#include <time.h>']:[]),...(mqtt?['#include <PubSubClient.h>']:[]),...(http?['#include <HTTPClient.h>']:[])];
let globals=`
// Networking is isolated from graph evaluation in a FreeRTOS worker.
static portMUX_TYPE ebNetMux=portMUX_INITIALIZER_UNLOCKED;
static float ebNetInput[${nodes.length}],ebNetOutput[${nodes.length}];
static uint32_t ebNetUpdated[${nodes.length}];
static QueueHandle_t ebNetLogQueue=nullptr;
static void ebLog(const char *text){if(!ebNetLogQueue)return;char line[96];snprintf(line,sizeof(line),"%s",text);xQueueSend(ebNetLogQueue,line,0);}
static void ebLogValue(const char *label,int value){char line[96];snprintf(line,sizeof(line),"%s %d",label,value);ebLog(line);}
static void ebPrintNetworkLog(){if(!ebNetLogQueue)return;char line[96];while(xQueueReceive(ebNetLogQueue,line,0)==pdTRUE)Serial.println(line);}
static float ebNetFreshRead(int i,uint32_t age){portENTER_CRITICAL(&ebNetMux);float v=ebNetOutput[i];uint32_t at=ebNetUpdated[i];portEXIT_CRITICAL(&ebNetMux);return uint32_t(millis()-at)>=age?NAN:v;}

static bool ebWifi=false,ebMqtt=false;
static float ebNetRead(int i){portENTER_CRITICAL(&ebNetMux);float v=ebNetOutput[i];portEXIT_CRITICAL(&ebNetMux);return v;}
static float ebNetValue(int i){portENTER_CRITICAL(&ebNetMux);float v=ebNetInput[i];portEXIT_CRITICAL(&ebNetMux);return v;}
static void ebNetInputSet(int i,float v){portENTER_CRITICAL(&ebNetMux);ebNetInput[i]=v;portEXIT_CRITICAL(&ebNetMux);}
static void ebNetOutputSet(int i,float v){portENTER_CRITICAL(&ebNetMux);ebNetOutput[i]=v;ebNetUpdated[i]=millis();portEXIT_CRITICAL(&ebNetMux);}
static void ebNetFlags(bool wifi,bool mqtt){portENTER_CRITICAL(&ebNetMux);ebWifi=wifi;ebMqtt=mqtt;portEXIT_CRITICAL(&ebNetMux);}
static float ebNetConnected(bool mqtt){portENTER_CRITICAL(&ebNetMux);bool result=mqtt?ebMqtt:ebWifi;portEXIT_CRITICAL(&ebNetMux);return result?1.0f:0.0f;}
static float ebParseNumber(const char *data,size_t len){if(!len||len>64||memchr(data,0,len))return NAN;char text[65];memcpy(text,data,len);text[len]=0;char *end;float v=float(strtod(text,&end));if(end==text)return NAN;while(*end&&isspace(static_cast<unsigned char>(*end)))end++;return *end||!isfinite(v)?NAN:v;}
${tls?'static const char ebRootCA[]='+q(cfg.rootCA)+';':''}
`;
if(mqtt){globals+=`${cfg.mqttTLS?'WiFiClientSecure':'WiFiClient'} ebMqttTransport; PubSubClient ebMqttClient(ebMqttTransport);\n`;for(const n of sub)globals+=`static uint32_t ebReceived${slot.get(n.id)}=0; static bool ebSeen${slot.get(n.id)}=false;\n`;globals+=`static void ebReceive(char *topic,byte *payload,unsigned int length){(void)topic;(void)payload;(void)length;\n`+sub.map(n=>`if(strcmp(topic,${q(n.props.topic)})==0){ebNetOutputSet(${slot.get(n.id)},ebParseNumber(reinterpret_cast<const char*>(payload),length));ebReceived${slot.get(n.id)}=millis();ebSeen${slot.get(n.id)}=true;}`).join('\n')+'\n}\n';}
if(http)globals+=`
class EBResponse:public Stream{public:char data[65]={};size_t length=0;bool overflow=false;int available()override{return 0;}int read()override{return -1;}int peek()override{return -1;}void flush()override{}size_t write(uint8_t v)override{return write(&v,1);}size_t write(const uint8_t *v,size_t size)override{if(length+size>64){overflow=true;return 0;}memcpy(data+length,v,size);length+=size;data[length]=0;return size;}};
static float ebHttp(const char *url,bool post,float input,bool statusOnly,int &code){
 if(WiFi.status()!=WL_CONNECTED){code=-1000;return statusOnly?float(code):NAN;}
 if(post&&!isfinite(input)){code=-1001;return float(code);}
 WiFiClient plain;${tls?'WiFiClientSecure secure;secure.setCACert(ebRootCA);secure.setHandshakeTimeout(5);':''}
 NetworkClient *client=&plain;${tls?'if(strncmp(url,"https:",6)==0)client=&secure;':''}
 client->setConnectionTimeout(${cfg.timeoutMs});HTTPClient request;request.setConnectTimeout(${cfg.timeoutMs});request.setTimeout(${cfg.timeoutMs});request.setFollowRedirects(HTTPC_DISABLE_FOLLOW_REDIRECTS);request.useHTTP10(true);
 if(!request.begin(*client,String(url))){code=-1003;return statusOnly?float(code):NAN;}
 if(strncmp(url,"https:",6)==0&&strlen(EB_HTTP_BEARER))request.addHeader("Authorization",String("Bearer ")+EB_HTTP_BEARER);
 if(post){request.addHeader("Content-Type","text/plain");code=request.POST(String(input,6));}else code=request.GET();
 float result=NAN;if(statusOnly)result=float(code);else if(code>=200&&code<300){EBResponse response;if(request.getSize()>64)code=-1002;else if(request.writeToStream(&response)>=0&&!response.overflow){result=ebParseNumber(response.data,response.length);if(!isfinite(result))code=-1001;}else code=-1002;}
 request.end();return result;
}
`;
let worker=`static void ebNetworkTask(void*){WiFi.persistent(false);WiFi.mode(WIFI_STA);WiFi.setAutoReconnect(true);WiFi.begin(${q(cfg.ssid)},EB_WIFI_PASSWORD);\n`;
if(tls)worker+=`configTime(0,0,${q(cfg.ntpHost)});\n`;
if(mqtt)worker+=`${cfg.mqttTLS?'ebMqttTransport.setCACert(ebRootCA);ebMqttTransport.setHandshakeTimeout(5);':''}ebMqttTransport.setConnectionTimeout(${cfg.timeoutMs});ebMqttClient.setServer(${q(cfg.mqttHost)},${cfg.mqttPort});ebMqttClient.setCallback(ebReceive);ebMqttClient.setSocketTimeout(${Math.ceil(cfg.timeoutMs/1000)});ebMqttClient.setKeepAlive(60);bool mqttBuffer=ebMqttClient.setBufferSize(512);uint64_t mac=ESP.getEfuseMac();char clientId[64];snprintf(clientId,sizeof(clientId),"%s-%08lx%08lx",${q(cfg.clientPrefix)},static_cast<unsigned long>(mac>>32),static_cast<unsigned long>(mac));uint32_t mqttAttempt=0;bool mqttFirst=true;int oldMqttState=-999;\n`;
worker+='uint32_t wifiAttempt=millis();int oldWifi=-1;\n';for(const n of nodes.filter(n=>['mqttPublish','httpGet','httpPost'].includes(n.type)))worker+=`uint32_t at${slot.get(n.id)}=0;bool first${slot.get(n.id)}=true;${n.type.startsWith('http')?`int oldHttp${slot.get(n.id)}=-999;`:''}\n`;
worker+=`for(;;){uint32_t now=millis();bool wifi=WiFi.status()==WL_CONNECTED;bool clockReady=${tls?'time(nullptr)>1700000000':'true'};if(int(wifi)!=oldWifi){oldWifi=wifi;ebLog(wifi?"NET Wi-Fi connected":"NET Wi-Fi disconnected");}if(!wifi&&uint32_t(now-wifiAttempt)>=${cfg.retryMs}UL){wifiAttempt=now;WiFi.reconnect();}\n`;
if(mqtt){worker+=`if(!wifi&&ebMqttClient.connected())ebMqttClient.disconnect();if(wifi&&${cfg.mqttTLS?'clockReady':'true'}&&mqttBuffer&&!ebMqttClient.connected()&&(mqttFirst||uint32_t(now-mqttAttempt)>=${cfg.retryMs}UL)){mqttFirst=false;mqttAttempt=now;bool connected=strlen(EB_MQTT_USERNAME)?ebMqttClient.connect(clientId,EB_MQTT_USERNAME,EB_MQTT_PASSWORD):ebMqttClient.connect(clientId);if(connected){bool subscribed=true;`+sub.map(n=>`subscribed=ebMqttClient.subscribe(${q(n.props.topic)},0)&&subscribed;`).join('')+`if(!subscribed)ebMqttClient.disconnect();}}ebMqttClient.loop();bool mqttUp=wifi&&ebMqttClient.connected();if(ebMqttClient.state()!=oldMqttState){oldMqttState=ebMqttClient.state();ebLogValue("NET MQTT state",oldMqttState);}ebNetFlags(wifi,mqttUp);\n`;for(const n of sub)worker+=`if(!mqttUp||!ebSeen${slot.get(n.id)}||uint32_t(millis()-ebReceived${slot.get(n.id)})>=${n.props.staleMs}UL)ebNetOutputSet(${slot.get(n.id)},NAN);\n`;}else worker+='ebNetFlags(wifi,false);\n';
for(const n of nodes){const k=slot.get(n.id),pr=n.props;if(n.type==='mqttPublish')worker+=`if(!mqttUp)ebNetOutputSet(${k},0);if(first${k}||uint32_t(millis()-at${k})>=${pr.interval}UL){first${k}=false;at${k}=millis();float value=ebNetValue(${k});bool sent=false;if(mqttUp&&isfinite(value)){char payload[48];snprintf(payload,sizeof(payload),"%.9g",double(value));sent=ebMqttClient.publish(${q(pr.topic)},payload,${pr.retain});}ebNetOutputSet(${k},sent?1:0);}\n`;
if(n.type.startsWith('http'))worker+=`if(first${k}||uint32_t(millis()-at${k})>=${pr.interval}UL){first${k}=false;at${k}=millis();int code;float value;if(!clockReady&&${/^https:/.test(pr.url)}){code=-1004;value=${n.type==='httpPost'||pr.result==='status'?'float(code)':'NAN'};}else value=ebHttp(${q(pr.url)},${n.type==='httpPost'},${n.type==='httpPost'?`ebNetValue(${k})`:'0'},${n.type==='httpPost'||pr.result==='status'},code);ebNetOutputSet(${k},value);if(code!=oldHttp${k}){oldHttp${k}=code;ebLogValue("NET HTTP ${n.id} status",code);}}\n`;}
worker+='(void)clockReady;vTaskDelay(pdMS_TO_TICKS(20));}}\n';globals+=worker;
const setup=[`ebNetLogQueue=xQueueCreate(8,96);for(int i=0;i<${nodes.length};i++){ebNetInput[i]=NAN;ebNetOutput[i]=NAN;} if(xTaskCreate(ebNetworkTask,"eb-network",12288,nullptr,1,nullptr)!=pdPASS) Serial.println("NET worker allocation failed");`];
return{includes,globals:[globals],setup,beforeLoop:['ebPrintNetworkLog();'],node(n,read){const k=slot.get(n.id),i=ix.get(n.id);if(n.type==='networkStatus')return`v${i}=ebNetConnected(${n.props.service==='mqtt'});`;return(['mqttPublish','httpPost'].includes(n.type)?`ebNetInputSet(${k},${read(n)}); `:'')+(n.type==='mqttSubscribe'?`v${i}=ebNetFreshRead(${k},${n.props.staleMs}UL);`:`v${i}=ebNetRead(${k});`);}};
}
const api={types,defaults,normalize,definitions,used,usesMQTT,issues,inputs,simulate,secretsHeader,generate};root.EBNetCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
