/* ELECTRONBENCH scenarios, modules, and revisions. GPL-3.0-only. */
'use strict';
(()=>{
const A=window.EBApp,E=window.EB,$=id=>document.getElementById(id),h=A.esc;
let recording=false,recorded=[],scenarioIndex=0,draft=null,result=null,scope='';
const strip=document.createElement('div');strip.className='group-strip';strip.innerHTML='<label for="diagramScope">Subdiagram</label><select id="diagramScope"><option value="">Entire project</option></select><span id="groupBoundary"></span>';document.querySelector('.studio-toolbar').after(strip);
const fieldValue=value=>value===null?'null':String(value);
function actualType(n){return E.defs[n.type].out||Object.values(E.defs[n.type].inputs||{})[0];}
function snapshot(){const p=E.clone(A.project);p.revisions=[];p.modules=[];return p;}
function options(selected,inputs=false){return A.project.nodes.filter(n=>!inputs||n.type==='button'||n.type==='analog'||E.defs[n.type].virtual).map(n=>`<option value="${n.id}" ${selected===n.id?'selected':''}>${h(n.label)}</option>`).join('');}
function parseValue(text,nodeId){if(text.trim()==='null')return null;const n=A.project.nodes.find(n=>n.id===nodeId);if(!n)throw Error('Choose a component.');if(actualType(n)==='boolean'){if(!['true','false'].includes(text.trim().toLowerCase()))throw Error('Boolean values must be true or false.');return text.trim().toLowerCase()==='true';}const value=Number(text);if(text.trim()===''||!Number.isFinite(value))throw Error('Enter a numeric value.');return value;}
function readDraft(){draft.name=$('scenarioName').value.trim()||'Scenario';draft.duration=Number($('scenarioDuration').value);for(const key of ['events','assertions'])draft[key]=[...$('scenario-'+key).querySelectorAll('tbody tr')].map(tr=>{const [time,node,value,tolerance]=tr.querySelectorAll('input,select');return{time:Number(time.value),node:node.value,value:parseValue(value.value,node.value),...(key==='assertions'?{tolerance:Number(tolerance.value)}:{})};});return E.normalizeScenario(draft,A.project);}
function defaultScenario(){const output=A.project.nodes.find(n=>!E.defs[n.type].out)||A.project.nodes[0];return{name:'New scenario',duration:2000,events:[],assertions:output?[{time:0,node:output.id,value:actualType(output)==='boolean'?true:0,tolerance:.01}]:[]};}
function rowTable(key){const assertions=key==='assertions';return`<div class="table-scroll"><table class="scenario-table" id="scenario-${key}"><thead><tr><th>Time · ms</th><th>${assertions?'Observe':'Input'}</th><th>${assertions?'Expected':'Value'}</th>${assertions?'<th>Tolerance</th>':''}<th></th></tr></thead><tbody>${draft[key].map((e,i)=>`<tr><td><input type="number" min="0" max="600000" step="10" value="${e.time}" aria-label="Time in milliseconds"></td><td><select aria-label="Component">${options(e.node,!assertions)}</select></td><td><input value="${h(fieldValue(e.value))}" aria-label="${assertions?'Expected value':'Input value'}"></td>${assertions?`<td><input type="number" min="0" step=".01" value="${e.tolerance??.01}" aria-label="Tolerance"></td>`:''}<td><button data-remove-row="${key}:${i}" aria-label="Remove row">×</button></td></tr>`).join('')}</tbody></table></div>`;}
function scenarios(){const list=A.project.scenarios||[];scenarioIndex=Math.min(scenarioIndex,Math.max(0,list.length-1));draft=E.clone(list[scenarioIndex]||defaultScenario());renderScenario();}
function renderScenario(){A.modal('Behavioral test scenarios',`<p>Apply timestamped virtual inputs and check expected outputs. Times use 10 ms increments. Use <code>true</code>/<code>false</code> for Boolean values; <code>null</code> models an invalid sensor reading or expects a non-finite output.</p><div class="scenario-toolbar"><select id="scenarioSelect" aria-label="Saved scenario"><option value="new">New scenario</option>${(A.project.scenarios||[]).map((s,i)=>`<option value="${i}" ${s.name===draft.name?'selected':''}>${h(s.name)}</option>`).join('')}</select><button id="saveScenario">Save scenario</button><button id="deleteScenario">Delete saved</button><button id="recordScenario">${recording?'Stop recording':'Record virtual inputs'}</button></div><label class="field"><span>Name</span><input id="scenarioName" value="${h(draft.name)}" maxlength="100"></label><label class="field"><span>Duration · milliseconds</span><input id="scenarioDuration" type="number" min="10" max="600000" step="10" value="${draft.duration}"></label><h3>Input events</h3>${rowTable('events')}<button id="addEvent">Add input event</button><h3>Expected outputs</h3>${rowTable('assertions')}<button id="addAssertion">Add expectation</button><div class="modal-actions"><button id="runScenario" class="primary">Run test</button><button id="exportScenarioResult">Save result</button></div><p id="scenarioMessage" role="status"></p><div id="scenarioResults"></div>`);
 $('scenarioSelect').onchange=e=>{if(e.target.value==='new'){draft=defaultScenario();scenarioIndex=-1;}else{scenarioIndex=Number(e.target.value);draft=E.clone(A.project.scenarios[scenarioIndex]);}renderScenario();};
 const capture=fn=>{try{readDraft();fn();renderScenario();}catch(e){$('scenarioMessage').textContent=e.message;}};
 $('addEvent').onclick=()=>capture(()=>{const n=A.project.nodes.find(n=>n.type==='button'||n.type==='analog'||E.defs[n.type].virtual);if(!n)throw Error('Add a button, analog input, or sensor first.');draft.events.push({time:0,node:n.id,value:actualType(n)==='boolean'?false:0});});
 $('addAssertion').onclick=()=>capture(()=>{const n=A.project.nodes.find(n=>n.id===A.selected)||A.project.nodes.at(-1);if(!n)throw Error('Add a component first.');draft.assertions.push({time:Math.min(draft.duration,A.simTime),node:n.id,value:A.sim?.values[n.id]??(actualType(n)==='boolean'?false:0),tolerance:.01});});
 $('modalBody').querySelectorAll('[data-remove-row]').forEach(b=>b.onclick=()=>capture(()=>{const [key,index]=b.dataset.removeRow.split(':');draft[key].splice(Number(index),1);}));
 $('saveScenario').onclick=()=>{try{const value=readDraft();A.edit(()=>{A.project.scenarios??=[];const index=A.project.scenarios.findIndex(t=>t.name===value.name);if(index>=0)A.project.scenarios[index]=value;else{if(A.project.scenarios.length>=30)throw Error('At most 30 scenarios per project.');A.project.scenarios.push(value);}scenarioIndex=A.project.scenarios.findIndex(t=>t.name===value.name);});$('scenarioMessage').textContent='Scenario saved with this project.';}catch(e){$('scenarioMessage').textContent=e.message;}};
 $('deleteScenario').onclick=()=>{if(scenarioIndex<0)return;A.edit(()=>A.project.scenarios.splice(scenarioIndex,1));scenarioIndex=0;scenarios();};
 $('recordScenario').onclick=()=>{if(recording){stopRecording();return;}recording=true;recorded=[];for(const n of A.project.nodes)if(n.type==='button'||n.type==='analog'||E.defs[n.type].virtual)recorded.push({time:0,node:n.id,value:A.inputs[n.id]??(n.type==='button'?false:E.virtual(n)?.value??Math.round(E.board(A.project).adcMax/2))});A.stopPreview(true);A.closeModal();A.setTab('preview');$('run').click();$('projectTools').classList.add('recording');$('projectTools').textContent='● Stop recording';A.say('Recording virtual inputs. Click Stop recording in Project tools when finished.');};
 $('runScenario').onclick=async()=>{try{const t=readDraft();$('runScenario').disabled=true;$('scenarioMessage').textContent='Running…';result=await executeScenario(t);const passed=result.assertions.filter(r=>r.pass).length;$('scenarioMessage').textContent=`${result.pass?'PASS':'REVIEW'} · ${passed}/${result.assertions.length} expectations passed. ${result.warning}`;$('scenarioResults').innerHTML='<table><thead><tr><th>Time</th><th>Signal</th><th>Expected</th><th>Actual</th><th>Result</th></tr></thead><tbody>'+result.assertions.map(r=>`<tr><td>${r.time}</td><td>${h(A.project.nodes.find(n=>n.id===r.node)?.label||r.node)}</td><td>${h(fieldValue(r.value))}</td><td>${h(fieldValue(r.actual))}</td><td class="${r.pass?'result-pass':'result-fail'}">${r.pass?'Pass':'Fail'}</td></tr>`).join('')+'</tbody></table>';}catch(e){if($('scenarioMessage'))$('scenarioMessage').textContent=e.message;}finally{if($('runScenario'))$('runScenario').disabled=false;}};
 $('exportScenarioResult').onclick=()=>{if(!result){$('scenarioMessage').textContent='Run a scenario first.';return;}A.download(JSON.stringify({version:E.VERSION,board:A.project.board,date:new Date().toISOString(),...result},null,2),'electronbench-scenario-result.json','application/json');};
}
function executeScenario(t){if(location.protocol==='file:'||!window.Worker){if(t.duration*A.project.nodes.length>5000000)return Promise.reject(Error('Serve the app on localhost to run this larger scenario in a worker.'));return Promise.resolve(E.runScenario(A.project,t));}return new Promise((resolve,reject)=>{const worker=new Worker('./scenario-worker.js'),timer=setTimeout(()=>{worker.terminate();reject(Error('Scenario exceeded 30 seconds. Shorten it or simplify the graph.'));},30000);worker.onmessage=({data})=>{clearTimeout(timer);worker.terminate();data.error?reject(Error(data.error)):resolve(data.result);};worker.onerror=e=>{clearTimeout(timer);worker.terminate();reject(Error(e.message||'Scenario worker failed.'));};worker.postMessage({project:A.project,scenario:t});});}
function recordInput(node,value,time){if(!recording)return;const event={time:Math.min(600000,Math.round(time/10)*10),node,value};const previous=recorded.at(-1);if(previous?.node===node&&previous.time===event.time)recorded[recorded.length-1]=event;else if(recorded.length<1000)recorded.push(event);}
function stopRecording(){recording=false;A.stopPreview();$('projectTools').classList.remove('recording');$('projectTools').textContent='Project tools';draft={name:'Recorded '+new Date().toLocaleTimeString(),duration:Math.min(600000,Math.max(10,Math.ceil(A.simTime/10)*10)),events:recorded,assertions:[]};scenarioIndex=-1;renderScenario();$('scenarioMessage').textContent='Inputs captured. Add expected outputs, then save and run the scenario.';}
const originalProjectTools=$('projectTools').onclick;$('projectTools').onclick=()=>recording?stopRecording():originalProjectTools();
function modules(){const list=A.project.modules||[];A.modal('Reusable modules and subdiagrams',`<p>A module captures selected components and their internal connections. Inserting it creates an editable subdiagram. Reassign conflicting pins and connect its exposed inputs in the inspector.</p><label class="field"><span>Module or subdiagram name</span><input id="moduleName" maxlength="80" placeholder="For example: debounced trigger"></label><div class="modal-actions"><button id="saveModule">Save selection as module</button><button id="groupSelection">Group selection</button><button id="ungroupSelection">Ungroup selection</button><button id="importModule">Import module</button></div><input id="moduleFile" type="file" accept=".json" hidden><p id="moduleMessage" role="status"></p><div>${list.map((m,i)=>`<div class="module-card"><strong>${h(m.name)}</strong><small>${m.project.nodes.length} components · ${h(E.board(m.project).name)}</small><div><button data-insert-module="${i}">Insert</button><button data-export-module="${i}">Export</button><button data-delete-module="${i}" class="danger">Delete template</button></div></div>`).join('')||'<p>No saved modules. Select components with Shift-click to create one.</p>'}</div>`);
 const getName=()=>$('moduleName').value.trim()||'Reusable behavior';const selected=()=>[...A.selection].length?[...A.selection]:A.selected?[A.selected]:[];
 $('saveModule').onclick=()=>{try{const module=E.makeModule(A.project,selected(),getName());A.edit(()=>{if(A.project.modules.length>=20)throw Error('At most 20 modules per project.');A.project.modules.push(module);});modules();}catch(e){$('moduleMessage').textContent=e.message;}};
 $('groupSelection').onclick=()=>{const ids=new Set(selected()),name=getName();if(!ids.size){$('moduleMessage').textContent='Select components first.';return;}A.edit(()=>A.project.nodes.filter(n=>ids.has(n.id)).forEach(n=>n.group=name));$('moduleMessage').textContent='Subdiagram created. Choose it from the canvas subdiagram selector.';};
 $('ungroupSelection').onclick=()=>{const ids=new Set(selected());A.edit(()=>A.project.nodes.filter(n=>ids.has(n.id)).forEach(n=>delete n.group));};
 $('modalBody').querySelectorAll('[data-insert-module]').forEach(b=>b.onclick=()=>{let ids;A.edit(()=>ids=E.insertModule(A.project,list[Number(b.dataset.insertModule)],A.uid));A.closeModal();scope=A.project.nodes.find(n=>n.id===ids[0]).group;A.select(ids[0]);refresh();A.fit();A.say('Module inserted. Resolve open inputs and pin conflicts in Checks.');});
 $('modalBody').querySelectorAll('[data-export-module]').forEach(b=>b.onclick=()=>A.download(JSON.stringify({format:'electronbench-module',schema:1,module:list[Number(b.dataset.exportModule)]},null,2),'electronbench-module.json','application/json'));
 $('modalBody').querySelectorAll('[data-delete-module]').forEach(b=>b.onclick=()=>{A.edit(()=>A.project.modules.splice(Number(b.dataset.deleteModule),1));modules();});
 $('importModule').onclick=()=>$('moduleFile').click();$('moduleFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Module file is too large.');const data=JSON.parse(await file.text());if(data.format!=='electronbench-module'||data.schema!==1)throw Error('Unsupported module file.');const project=E.importProject(data.module.project,1),m={name:String(data.module.name||project.name).slice(0,100),date:new Date().toISOString(),project};A.edit(()=>{if(A.project.modules.length>=20)throw Error('At most 20 modules per project.');A.project.modules.push(m);});modules();}catch(error){$('moduleMessage').textContent=error.message;}};
}
function revisions(){const p=A.project;A.modal('Revisions and evidence',`<p>Save a baseline before changing a working program. Comparison focuses on behavior, wiring, and settings. Layout-only moves are omitted.</p><label class="field"><span>Revision name</span><input id="revisionName" maxlength="100" placeholder="For example: first working sensor"></label><button id="saveRevision">Save baseline</button><div>${p.revisions.map((r,i)=>`<div class="module-card"><strong>${h(r.name)}</strong><small>${h(r.date)}</small><div><button data-compare="${i}">Compare with current</button><button data-restore="${i}">Restore</button><button data-delete-revision="${i}">Delete baseline</button></div></div>`).join('')}</div><div id="revisionDiff"></div><h3>Evidence register</h3><p class="modal-subtitle">These are user-recorded observations. They do not automatically certify a board or circuit.</p><label class="field"><span>Evidence type</span><select id="evidenceKind"><option>Physical board test</option><option>Compiler result</option><option>Wiring inspection</option><option>Other observation</option></select></label><label class="field"><span>Observation / board / outcome</span><textarea id="evidenceNote" maxlength="5000"></textarea></label><button id="addEvidence">Record evidence</button><p id="revisionMessage"></p><div>${p.evidence.map((e,i)=>`<div class="module-card"><strong>${h(e.kind)}</strong><small>${h(e.date)}</small><p>${h(e.note)}</p><button data-remove-evidence="${i}">Remove entry</button></div>`).join('')}</div><h3>Assumptions register</h3><p>Record expectations that have not been established by evidence.</p><label class="field"><span>Assumption</span><textarea id="assumptionNote" maxlength="5000"></textarea></label><button id="addAssumption">Record assumption</button><div>${p.assumptions.map((e,i)=>`<div class="module-card"><small>${h(e.date)}</small><p>${h(e.note)}</p><button data-remove-assumption="${i}">Remove assumption</button></div>`).join('')}</div>`);
 $('addAssumption').onclick=()=>{const note=$('assumptionNote').value.trim();if(!note||p.assumptions.length>=100){$('revisionMessage').textContent=note?'Assumptions register is full.':'Enter an assumption first.';return;}A.edit(()=>p.assumptions.push({date:new Date().toISOString(),note}));revisions();};
 $('modalBody').querySelectorAll('[data-remove-assumption]').forEach(b=>b.onclick=()=>{A.edit(()=>p.assumptions.splice(Number(b.dataset.removeAssumption),1));revisions();});
 $('saveRevision').onclick=()=>{const name=$('revisionName').value.trim()||'Baseline '+(p.revisions.length+1);if(p.revisions.length>=10){$('revisionMessage').textContent='Export your project or remove a baseline before adding an eleventh.';return;}const project=snapshot();A.edit(()=>p.revisions.push({name,date:new Date().toISOString(),project}));revisions();};
 $('modalBody').querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const changes=E.diffProjects(p.revisions[Number(b.dataset.compare)].project,p);$('revisionDiff').innerHTML=changes.length?'<table><tr><th>Change</th><th>Item</th></tr>'+changes.map(c=>`<tr><td>${h(c.kind)}</td><td>${h(c.item)}</td></tr>`).join('')+'</table>':'<p>No behavioral, wiring, or settings changes.</p>';});
 $('modalBody').querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const restored=E.importProject(p.revisions[Number(b.dataset.restore)].project);restored.revisions=E.clone(p.revisions);restored.modules=E.clone(p.modules);A.replaceProject(restored);A.closeModal();A.say('Baseline restored. Undo returns to your previous project.');});
 $('modalBody').querySelectorAll('[data-delete-revision]').forEach(b=>b.onclick=()=>{A.edit(()=>p.revisions.splice(Number(b.dataset.deleteRevision),1));revisions();});
 $('addEvidence').onclick=()=>{const note=$('evidenceNote').value.trim();if(!note){$('revisionMessage').textContent='Enter an observation first.';return;}if(p.evidence.length>=100){$('revisionMessage').textContent='Evidence register is full. Export the project first.';return;}const entry={kind:$('evidenceKind').value,date:new Date().toISOString(),note};A.edit(()=>p.evidence.push(entry));revisions();};
 $('modalBody').querySelectorAll('[data-remove-evidence]').forEach(b=>b.onclick=()=>{A.edit(()=>p.evidence.splice(Number(b.dataset.removeEvidence),1));revisions();});
}
function bundle(){try{const p=A.project,source=E.generate(p),files={'electronbench_project/electronbench_project.ino':source,'electronbench_project/sketch.yaml':E.buildProfile(p),'project.electronbench.json':JSON.stringify(p,null,2),'dependencies.json':JSON.stringify({board:E.fqbn(p),libraries:E.dependencies(p)},null,2),'checks.json':JSON.stringify(E.validate(p).issues,null,2),'README.txt':`ELECTRONBENCH ${E.VERSION}\nProject: ${p.name}\nTarget: ${E.board(p).name}\n\nOpen the sketch folder in Arduino IDE, or compile with:\narduino-cli compile --profile electronbench electronbench_project\n\nProject JSON is the editable visual source. Preserve it. Network projects include an empty electronbench_secrets.h; download your filled header from Network settings and keep it private.\nBrowser preview is behavioral; validate physical hardware separately.\n\nNotes:\n${p.notes}\n\nGenerated code and application: GPL-3.0-only. External libraries retain their own licenses.\n`};if(E.network.used(p))files['electronbench_project/electronbench_secrets.h']=E.network.secretsHeader();A.download(EBZip.pack(files),'electronbench-project-bundle.zip','application/zip');A.say('Project, firmware, pinned profile, dependencies, and checks exported together.');}catch(e){A.say(e.message);A.setTab('checks');}}
function refresh(){const groups=[...new Set(A.project.nodes.map(n=>n.group).filter(Boolean))].sort();if(!groups.includes(scope))scope='';$('diagramScope').innerHTML='<option value="">Entire project</option>'+groups.map(g=>`<option value="${h(g)}" ${g===scope?'selected':''}>${h(g)}</option>`).join('');for(const el of $('nodes').querySelectorAll('.node')){const n=A.project.nodes.find(n=>n.id===el.dataset.node);el.hidden=!!scope&&n.group!==scope;}const visible=new Set(A.project.nodes.filter(n=>!scope||n.group===scope).map(n=>n.id)),external=A.project.edges.filter(e=>visible.has(e.from)!==visible.has(e.to)).length;$('groupBoundary').textContent=scope?`${visible.size} components · ${external} external connections (available in inspector)`:'Modules flatten into one program when compiled.';strip.hidden=!groups.length;}
$('diagramScope').onchange=e=>{scope=e.target.value;A.render();if(scope){const ns=A.project.nodes.filter(n=>n.group===scope);const minX=Math.min(...ns.map(n=>n.x)),minY=Math.min(...ns.map(n=>n.y));A.project.view={zoom:.8,x:60-minX*.8,y:60-minY*.8};A.render();A.mark();}else A.fit();};
window.EBProjectTools={scenarios,modules,revisions,bundle,recordInput,refresh,get recording(){return recording;},get scope(){return scope;}};refresh();
})();
