/* Real Arduino CLI compile checks. Set ELECTRONBENCH_ARDUINO_CLI and optionally ELECTRONBENCH_ARDUINO_CONFIG. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');const {spawnSync}=require('node:child_process');
const {E,behaviors,feedback,peripherals,uart,starter,expandedSensors,networking}=require('./fixtures.cjs');
const cli=process.env.ELECTRONBENCH_ARDUINO_CLI||'arduino-cli',config=process.env.ELECTRONBENCH_ARDUINO_CONFIG;
const selected=process.argv.slice(2).filter(x=>Object.hasOwn(E.boards,x));const boards=selected.length?selected:Object.keys(E.boards),temp=fs.mkdtempSync(path.join(os.tmpdir(),'electronbench-compile-')),results=[];
const env={...process.env,ARDUINO_NETWORK_PROXY:process.env.ARDUINO_NETWORK_PROXY||process.env.HTTPS_PROXY||'',ARDUINO_METRICS_ENABLED:'false'};
for(const board of boards){const cases={blink:starter('blink',board),servo:starter('servo',board),button:starter('button',board),display:starter('sensor',board),behaviors:behaviors(board),feedback:feedback(board),peripherals:peripherals(board),expandedSensors:expandedSensors(board)};if(E.boards[board].uart.length)cases.uart=uart(board);if(E.isESP(board)){cases.network=networking(board);cases.networkTLS=networking(board,true);}
 for(const [name,p]of Object.entries(cases)){if(process.env.ELECTRONBENCH_FIXTURE&&name!==process.env.ELECTRONBENCH_FIXTURE)continue;const check=E.validate(p);if(!check.valid)throw Error(JSON.stringify(check.issues));const dir=path.join(temp,board+'_'+name);fs.mkdirSync(dir);const ino=path.join(dir,path.basename(dir)+'.ino');fs.writeFileSync(ino,E.generate(p));if(process.env.ELECTRONBENCH_PINNED==='1')fs.writeFileSync(path.join(dir,'sketch.yaml'),E.buildProfile(p));
 if(E.network.used(p))fs.writeFileSync(path.join(dir,'electronbench_secrets.h'),E.network.secretsHeader());
 const args=['compile',...(process.env.ELECTRONBENCH_PINNED==='1'?['--profile','electronbench']:['--fqbn',E.fqbn(p)]),'--warnings','all',...(config?['--config-file',config]:[]),dir];
 const result=spawnSync(cli,args,{encoding:'utf8',env,timeout:15*60*1000,maxBuffer:5e6});const log=(result.stdout||'')+(result.stderr||'');const status=result.status===0?'PASS':'FAIL';const memory=log.split('\n').filter(s=>/Sketch uses|Global variables use|Program size/.test(s));results.push({board,fixture:name,pass:result.status===0,memory,log});console.log(status,board,name,memory.join(' | '));if(result.status!==0){console.error(log.slice(-9000));fs.writeFileSync(process.env.ELECTRONBENCH_MATRIX_REPORT||path.join(temp,'results.json'),JSON.stringify(results,null,2));process.exitCode=1;break;}
 }if(process.exitCode)break;
}
const report=process.env.ELECTRONBENCH_MATRIX_REPORT||path.join(temp,'results.json');fs.writeFileSync(report,JSON.stringify({date:new Date().toISOString(),version:E.VERSION,mode:process.env.ELECTRONBENCH_PINNED==='1'?'pinned profiles':'installed toolchains',results},null,2));console.log('Compiler report:',report);console.log(`${results.filter(r=>r.pass).length}/${results.length} real target compiles passed. No physical upload performed.`);
