const fs=require('node:fs'),path=require('node:path');
const appDir=fs.existsSync(path.join(__dirname,'../dist/core.js'))?path.join(__dirname,'../dist'):path.join(__dirname,'..');require(path.join(appDir,'core.js'));const E=globalThis.EB;
function graph(board='uno-r3'){const p=E.blank();p.board=board;let n=0,e=0;return{p,add(type,props={}){const node=E.makeNode(type,'n'+(++n),n*40,100,board);Object.assign(node.props,props);p.nodes.push(node);return node;},link(a,b,port='in'){p.edges.push({id:'e'+(++e),from:a.id,to:b.id,port});}};}
function behaviors(board='uno-r3'){
 const g=graph(board),value=g.add('constant',{value:12}),yes=g.add('boolean',{value:true}),no=g.add('boolean',{value:false});
 for(const type of ['math','clamp','smooth','hysteresis','valid','select','rising','falling','counter','latch','sequence','custom']){const n=g.add(type);if(type==='custom')n.props.preview=12;for(const [port,t]of Object.entries(E.defs[type].inputs||{}))g.link(t==='number'?value:(port==='reset'?no:yes),n,port);}
 const pwm=g.add('pwm');g.link(value,pwm);g.p.settings.telemetry=true;return g.p;
}
function feedback(board='uno-r3'){const g=graph(board),memory=g.add('memory',{initial:0}),one=g.add('constant',{value:1}),add=g.add('math'),probe=g.add('probe');g.link(memory,add,'a');g.link(one,add,'b');g.link(add,memory);g.link(memory,probe);return g.p;}
function peripherals(board='uno-r3'){const g=graph(board);g.add('mcp9808');g.add('bh1750');g.add('max31855',{pin:board==='esp32-devkitc'?'27':board==='esp32-s3-devkitc'?'10':'10'});g.p.settings.telemetry=true;return g.p;}
function uart(board='mega-2560'){const g=graph(board),read=g.add('uart'),probe=g.add('probe');g.link(read,probe);return g.p;}
function starter(name,board){const p=E.sample(name);p.board=board;if(E.isESP(board)){for(const n of p.nodes){if(n.type==='led')n.props.pin=board==='esp32-devkitc'?'25':'4';if(n.type==='button')n.props.pin=board==='esp32-devkitc'?'26':'5';if(n.type==='analog')n.props.pin=E.board(board).analog[0];if(n.type==='servo')n.props.pin=board==='esp32-devkitc'?'27':'6';if(n.type==='map')n.props.inMax=4095;}}return p;}
function expandedSensors(board='uno-r3'){const g=graph(board);for(const measurement of ['temperature','humidity','pressure'])g.add('bme280',{measurement});for(const measurement of ['voltage','current','power'])g.add('ina219',{measurement});g.p.settings.telemetry=true;return g.p;}
function networking(board='esp32-devkitc',secure=false){const g=graph(board),value=g.add('bme280'),pub=g.add('mqttPublish'),sub=g.add('mqttSubscribe'),post=g.add('httpPost'),get=g.add('httpGet');g.link(value,pub);g.link(value,post);g.add('networkStatus',{service:'wifi'});g.add('networkStatus',{service:'mqtt'});g.link(sub,g.add('probe'));g.link(get,g.add('probe'));g.p.network={...E.network.defaults(),ssid:'TEST_SSID',mqttHost:'broker.example',mqttTLS:secure,mqttPort:secure?8883:1883,rootCA:secure?'-----BEGIN CERTIFICATE-----\nTEST_ONLY_NOT_A_VALID_CERTIFICATE\n-----END CERTIFICATE-----':''};if(secure)for(const n of [post,get])n.props.url='https://example.com/value';g.p.settings.telemetry=true;return g.p;}
module.exports={networking,expandedSensors,E,graph,behaviors,feedback,peripherals,uart,starter,appDir};
