/* Service-worker logic with mocked cache APIs; not browser offline verification. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),vm=require('node:vm');const {appDir,E}=require('./fixtures.cjs');
(async()=>{const events={},cached=new Map(),deleted=[],scope='https://example.test/projects/electronbench/',self={addEventListener:(name,fn)=>events[name]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}}};
const caches={open:async()=>({addAll:async files=>{for(const file of files){const local=file==='./'?'index.html':file.replace('./','');assert.ok(fs.existsSync(path.join(appDir,local)),file);cached.set(new URL(file,scope).href,{name:file});}}}),keys:async()=>['unrelated-cache','electronbench-v0.1.0','electronbench-v'+E.VERSION],delete:async name=>{deleted.push(name);return true},match:async request=>cached.get(request.url)};
vm.runInNewContext(fs.readFileSync(path.join(appDir,'sw.js'),'utf8'),{self,caches,location:new URL(scope),URL,fetch:async()=>{throw Error('Network offline')}});
let work;events.install({waitUntil:p=>work=p});await work;for(const name of [...fs.readFileSync(path.join(appDir,'index.html'),'utf8').matchAll(/(?:src|href)="([^"]+\.(?:js|css))"/g)].map(m=>m[1]).concat(['index.html','scenario-worker.js']))assert.ok(cached.has(scope+name));console.log('PASS cache installation includes all editor and worker modules');
events.activate({waitUntil:p=>work=p});await work;assert.deepEqual(deleted,['electronbench-v0.1.0']);console.log('PASS activation only removes previous ELECTRONBENCH cache versions');
let response;events.fetch({request:{url:scope+'scenario-worker.js',method:'GET'},respondWith:p=>response=p});assert.equal((await response).name,'./scenario-worker.js');for(const url of [scope+'api/job','https://elsewhere.test/core.js'])events.fetch({request:{url,method:'GET'},respondWith:()=>{throw Error('API or third-party request was intercepted')}});console.log('PASS cached subdirectory assets resolve offline in cache double; API and other origins bypass it');
console.log('3 platform test groups passed using cache doubles. Actual browser cache lifecycle and offline reload remain unverified.');
})().catch(e=>{console.error(e);process.exitCode=1;});
